#!/usr/bin/env ruby

require 'Blast'

if (ARGV.size != 2)
  STDERR.printf("usage: %s recip-file blast-file\n", $0)
  exit(1)
end

recip, blast = ARGV

orths = Hash.new

File.new(recip).each {|line|
  fwd, rev, fp, rp, orth = line.chomp.split("\t")
  orths[fwd] = rev if (orth == "yes")
}


Blast.new(blast).each {|query|
  if (orths[query.name])
    query.each {|hit|
      print hit.qmatch.to_fasta(query.name + " " + hit.pvalue.to_s, 60)
      print hit.smatch.to_fasta(orths[query.name] + " " + hit.pvalue.to_s, 60)
      break
    }
  end
}
