#!/usr/bin/env ruby

require 'optparse'
require 'rubygems'
require'bio'    

ARGV.options {|opts|
  opts.banner << " fasta ent"
  begin
    opts.parse!
  rescue
    STDERR.puts $!.message
    STDERR.puts opts
    exit(1)
  end
  if (ARGV.size != 2)
    STDERR.puts opts
    exit(1)
  end
}
 
fasta, ent = ARGV

starts = Hash.new
ends = Hash.new
descs = Hash.new

File.new(ent).each {|line|
  orf, d, s, e, f, desc = line.chomp.split("\t")
  s, e = e,s if f == "-1"
  starts[orf] = s
  ends[orf] = e
  descs[orf] = desc
}
  
Bio::FlatFile.new(Bio::FastaFormat, File.new(fasta)).each {|seq|
  orf = seq.entry_id
  header = orf + " " + starts[orf] + "_" + ends[orf] + " " + descs[orf]
  print Bio::Sequence::AA.new(seq.seq).to_fasta(header, 60)
}

