#!/usr/bin/env ruby

require 'csv'

if (ARGV.size < 2)
	STDERR.printf("Usage: %s Trina.csv bio.csv [bio.csv...]\n", File.basename($0))
	exit(1)
end

trina = ARGV.shift

STDERR.printf("Loading Trina...\n")
trpkm = Hash.new
sites = Hash.new

CSV.foreach(trina, :headers=>true) do |row|
	row = row.to_hash
	tid = row["Feature ID"]
	trpkm[tid] = Hash.new if (!trpkm[tid])
	row.keys.grep(/RPKM/).each do |key|
		r, site = key.split
		trpkm[tid][site] = row[key]
		sites[site] = true
	end
end

STDERR.printf("Processing csvs...\n")
ARGV.each do |csv|
	if csv =~/-(.*).csv/
		site = $1
		if !sites[site]
			printf("Warning! No data for %s!\n", site)
			next
		else
			headPrint = false
			outName = File.basename(csv, ".csv") + "_with_Trina.csv"
			out = File.new(outName, "w")
			CSV.foreach(csv) do |row|
				row = row.to_a
				if (!headPrint)
					row.insert(2, "Trina's RPKM")
					out.print row.to_csv
					headPrint = true
				else
					tr = nil
					if (trpkm[row.first])
						tr=trpkm[row.first][site]
					end
					row.insert(2, tr)
					out.print row.to_csv
				end
			end
			out.close
		end
	end
end