#!/usr/bin/env ruby 

require 'rubygems'
require 'bio'    
require 'trollop'
require 'ZFile'
require 'Btab'

ARGV.push("--help") if ARGV.empty?
opts = Trollop::options do
  banner File.basename($0)
  opt :input, "two blast files to compare", :required=>true, :type=>:strings
  opt :evalue, "evalue cutoff", :default=>0.1, :type=>:float
end

def processBlast(blast, names, hitName, hitVal, evalue)
  names[blast] = []
  Bio::Blast::Default::Report.open(blast, "r").each do |query|
    qname = query.query_def.split(" ").first
    names[blast].push(qname)
    query.each do |hit|
      hname =  hit.definition.split(" ").first
      evalue = hit.evalue
      coverage = hit.overlap / (0.01 * query.query_len)
      identity = hit.identity / (0.01 * hit.overlap)
      if evalue > evalue
        hitName[qname] = "xxx"
        hitVal[qname] = "xxx"
      else
        hitName[qname] = hname
        hitVal[qname] = hit.evalue
      end
      break
    end
  end
end

def processBtab(blast, names, hitName, hitVal, evalue)
  names[blast] = []
  Btab.new(blast).each do |query|
    names[blast].push(query.name)
    match = query.matches.first
    if match.name == "" || match.evalue > evalue
      hitName[query.name] = "xxx"
      hitVal[query.name] = "xxx"
    else
      hitName[query.name] = match.name
      hitVal[query.name] = match.evalue
    end
  end
end

blast1, blast2 = opts.input

hitName = Hash.new
hitVal = Hash.new
names = Hash.new

if blast1 =~/btab/
  processBtab(blast1, names, hitName, hitVal, opts.evalue)
  processBtab(blast2, names, hitName, hitVal, opts.evalue)
else
  processBlast(blast1, names, hitName, hitVal, opts.evalue)
  processBlast(blast2, names, hitName, hitVal, opts.evalue)
end

names[blast1].sort.each do |name|
  if (hitName[hitName[name]] == name)
    bestR = "yes"
  else
    bestR = "no"
  end
  printf("%s\t%s\t%s\t%s\t%s\n", name, hitName[name], hitVal[name],
	 hitVal[hitName[name]], bestR)  
end
