#!/usr/bin/env ruby
require 'optimist'

ARGV.push("--help") if ARGV.empty?
opts = Optimist::options do
  banner File.basename($0)
  opt :input, "files to list", :required=>true, :type=>:string
  opt :num, "just return number", :default=>false
end

files = Dir.glob(opts.input)

if opts.num
  print files.length
  print "\n"
else
  files.each do |file|
    print file + "\n"
  end
end