#!/usr/bin/env ruby

require 'rubygems'
require'bio'
require 'Phylogeny'

if (ARGV.size < 1)
  STDERR.printf("usage: %s blast-file [blast-file...]\n", $0)
  exit(1)
end

ecList = loadEC("/home/jbadger/EVOL/jbadger/EC.list")

ARGV.each {|file|
  report = Bio::Blast::WU::Report.open(file, "r").each {|query|
    name, rest = query.query_def.split(" ")
    query.each {|hit|
      hname, rest = hit.target_def.split(" ", 2)
      next if ((hit.identity*1.0)/query.query_len > 0.98)
      rest =~ /\[EC:([^]]*)\]/
      ec = $1.split(" ").first
      print "#{name}\t#{ec}\t#{ecList[ec]}\n" 
      break
    }
  }
}
