#!/usr/bin/env ruby 

require 'optimist'
require 'bio'

ARGV.push("--help") if ARGV.empty?
opts = Optimist::options do
  banner File.basename($0)
  opt :input, "input taxa", :required=>true, :type=>:string
end

ali = Hash.new
seen = Hash.new

out = File.new("ali.txt", "w")
File.new(opts.input).each do |line|
  num, tx = line.chomp.split("\t")
  sp = tx.split(";").last
  g, sp = sp.split(" ")
  abbr = (g[0..1] + sp[0..1]).upcase
  while seen[abbr]
    if abbr[3].to_i == 0
      abbr = abbr[0..2] + "0"
    end
    abbr.succ!
  end
  ali[num] = abbr
  seen[abbr] = true
  out.print [num, tx, abbr].join("\t") + "\n"
end
out.close

