#!/usr/bin/env ruby

require 'ostruct'
require 'optparse'
require 'rubygems'
require 'gchart'
require 'apis'
opt = OpenStruct.new

opt.storage = "misc_apis"
opt.host = "mysql-lan-pro.jcvi.org"

ARGV.options {|opts|
  opts.banner << " dataset tab-file"
  opts.on("-s ", "--storage ", String, "storage database (default #{opt.storage})") {|t| opt.storage = t}
  opts.on("-h ", "--host ", String, "database host (default #{opt.host})")
  begin
    opts.parse!
  rescue
    STDERR.puts $!.message
    STDERR.puts opts
    exit(1)
  end
  if (ARGV.size != 2)
    STDERR.puts opts
    exit(1)
  end
}

if (opt.storage == "")
  STDERR.printf("A storage database must be specified\n")
  exit(1)
end

dataset, tab = ARGV

storage = MySQL.new(opt.host, opt.storage, "apis", "apis_user")


ec = Hash.new
storage.query("select seq_name from sequence where dataset='#{dataset}'").each {|row|
  ec[row[0]] = ""
}

File.new(tab).each {|line|
  name, num, n, evalue = line.chomp.split("\t")
  evalue = evalue.to_f
  if (evalue < 1e-5)
    if (name=~/jgi\|([^\|]*)\|([0-9]*)/)
      name = "ORF" + $2 + "-" + $1
      if (ec[name] == "")
        ec[name] = num
      end
    end
  end
}

ec.keys.sort.each {|key|
  printf("%s\t%s\t%s\t%s\n", key, dataset, ec[key], "EC") if ec[key] != ""
}
