#!/usr/bin/env ruby

require 'optparse'
require 'ostruct'
require 'Btab'
require 'csv'

opt = OpenStruct.new
o = OptionParser.new
o.banner << " btab [..btab...]"
o.on("-v", "--verbose", "Run verbosely") {opt.verbose = true}
begin
  o.parse!
rescue
  STDERR << $!.message << "\n"
  STDERR << o
  exit(1)
end
if (ARGV.size < 1)
  STDERR << o
  exit(1)
end


hits = Hash.new
categories = []
ARGV.each do |btab|
  source, target = btab.split("_vs_")
  source = source.split(".").first
  target = target.split(".").first
  categories.push(source) if (!categories.include?(source))
  categories.push(target) if (!categories.include?(target))
  Btab.new(btab).each do |query|
    hits[query.name] = Hash.new if (!hits[query.name])
    hits[query.name][target] = query.matches.first.name
    hits[query.name][source] = query.name
  end
end

print (["Representative"] + categories).to_csv
hits.keys.sort.each do |hit|
  row = [hit]
  categories.each do |category|
    row.push(hits[hit][category])
  end
  print row.to_csv
end