#!/usr/bin/env ruby

require 'rubygems'
require 'bio'
require 'DBwrapper'

db = MySQL.new("mysql-lan-pro", "combodb", "apis", "apis_user")

query = "SELECT species, taxonomy, rrnas.seq FROM contigs, rrnas WHERE contigs.name = contig_name AND "
query += "annotation LIKE '%16S%' AND length(rrnas.seq) > 800"

seen = Hash.new
db.query(query).each do |row|
  species, taxonomy, seq = row
  next if seen[species]
  taxonomy.gsub!("; ", ";")
  taxonomy.gsub!(" ","_")
  species.gsub!(" ", "_")
  next if seen[species]
  print Bio::Sequence::NA.new(seq).to_fasta(species + " " + taxonomy, 60)
  seen[species] = true
end

db.close