#!/usr/bin/env ruby

require 'ostruct'
require 'optparse'
opt = OpenStruct.new

ARGV.options {|opts|
  opts.banner << " gb [gb...]"
  #opts.on(nil, "--report", "run apisReport when done") {|t| opt.report = t}    
  begin
    opts.parse!
  rescue
    STDERR.puts $!.message
    STDERR.puts opts
    exit(1)
  end
  if (ARGV.size < 1)
    STDERR.puts opts
    exit(1)
  end
}

name = nil

ARGV.each {|gb|
  gbname = File.basename(gb, ".gb")
  File.new(gb).each {|line|
    if (line =~/\/gene=\"([^\"]*)\"/)
      name = $1
    elsif (line =~/\/note=\"([^\"]*)\"/)
      printf("%s-%s\t%s\n", name, gbname, $1)
    end
  }
}
