#!/usr/bin/env ruby

require 'bio'
require 'trollop'

ARGV.push("--help") if ARGV.empty?
opts = Trollop::options do
  banner File.basename($0)
  opt :input, "Input alignment file(s)", :required=>true, :type=>:strings
  opt :phylip, "use PHYLIP format for input"
end


if opts.phylip
  Alignment = Bio::Phylip::PhylipFormat
else
  Alignment = Bio::Alignment::MultiFastaFormat
end

keys = []
opts.input.each do |file|
  aln = Alignment.new(File.read(file)).alignment
  keys += aln.keys
end
keys = keys.sort.uniq

multi = Hash.new
opts.input.each do |file|
  aln = Alignment.new(File.read(file)).alignment
  seen = Hash.new
  keys.each do |key|
    multi[key] = "" if !multi[key]
    if aln.keys.include?(key)
      multi[key] += aln[key]
    else
      multi[key] += "-" * aln[aln.keys.first].length
    end
  end
end

keys.each do |key|
  print Bio::Sequence::AA.new(multi[key]).to_fasta(key, 60)
end
