#!/usr/bin/env ruby

require 'trollop'

ARGV.push("--help") if ARGV.empty?
opts = Trollop::options do
  banner File.basename($0)
  opt :input, "name of cluster file", :required=>true, :type=>:string
end

cluster = Hash.new
num = nil
samples = []

File.new(opts.input).each do |line|
  if (line=~/^>Cluster (.*)/)
    num = $1.to_i
    cluster[num] = Hash.new
  elsif (line=~/>(.*)\.\.\./)
    pep = $1
    sample = pep.split("|").first
    samples.push(sample) if (!samples.include?(sample))
    cluster[num][sample] = Array.new if (cluster[num][sample].nil?)
    cluster[num][sample].push(pep)
  end
end

print (["Cluster", "Size"] + samples).join("\t")+"\n"
cluster.keys.each do |num|
  row = [num, 0]
  pos = 2
  samples.each do |samp|
    if cluster[num][samp]
      row[pos] = cluster[num][samp].join(" ")
      row[1] += cluster[num][samp].size
    end
    pos += 1
  end
  print row.join("\t")+"\n"
end
