#!/usr/bin/env ruby


if (ARGV.size != 2)
  STDERR.printf("Usage: %s old-transporters.txt new-transporters.txt\n", File.basename($0))
  exit(1)
end

old, newer = ARGV

oldHash = Hash.new
newerHash = Hash.new

File.new(old).each do |line|
  oldHash[line.split("\t").first] = line
end

File.new(newer).each do |line|
  newerHash[line.split("\t").first] = line
end


olduniq = oldHash.keys - newerHash.keys
neweruniq = newerHash.keys - oldHash.keys

STDERR.printf("%d uniq to %s. %d unique to %s\n", olduniq.size, old,
  neweruniq.size, newer)


out = File.new(old + "_uniq.txt", "w")
olduniq.sort.each do |key|
  out.print oldHash[key]
end
out.close

out = File.new(newer + "_uniq.txt", "w")
neweruniq.sort.each do |key|
  out.print newerHash[key]
end
out.close
