#!/usr/bin/env ruby

require 'optparse'
require 'rubygems'
require 'active_record'
require 'rubygems'
require'bio'
require 'MySQL'

@delete = false


ARGV.options {|opts|
  opts.banner << " MooreGenomes.csv"
  begin
    opts.parse!
  rescue
    STDERR.puts $!.message
    STDERR.puts opts
    exit(1)
  end
  if (ARGV.size != 1)
    STDERR.puts opts
    exit(1)
  end
}

db = MySQL.new
moore, rest = ARGV


File.new(moore).each {|line|
  phy, species, strain = line.split(",")
  contigs = Contig.find(:all, :conditions => "species like \"%#{species}%\" && strain like \"%#{strain}%\"")
  if (!contigs.empty?)
    printf("%s %s\n", species, strain)
  end
}
