#!/usr/bin/env ruby

require 'ostruct'
require 'optparse'
require 'bio'
require 'CodonBias'
opt = OpenStruct.new

opt.everything = false
opt.database = "combodb"
opt.taxonomy = false

ARGV.options do |opts|
  opts.banner << " cds"
  begin
    opts.parse!
  rescue
    STDERR.puts $!.message
    STDERR.puts opts
    exit(1)
  end
  if (ARGV.size < 1)
    STDERR.puts opts
    exit(1)
  end
end

Bio::FlatFile.new(Bio::FastaFormat, File.new(ARGV.first)).each do |seq|
  bias = CodonBias.new
  bias.add(seq.seq.upcase)
  bias.normalize
  printf("%s",seq.entry_id)
  bias.counts.each do |num|
    printf(",%0.6f",num)
  end
  printf("\n")
end
