#!/usr/bin/env ruby 

require 'rubygems'
require 'bio'    
require 'trollop'
require 'Newick'

ARGV.push("--help") if ARGV.empty?
opts = Trollop::options do
  banner File.basename($0)
  opt :input, "Input Newick file", :required=>true, :type=>:string
  opt :round, "Don't convert to bootstraps, just round"
end

tree = NewickTree.fromFile(opts.input)
tree.root.descendants.each do |node|
	if (node.name =~/^[0-9].[0-9]*/)
		if (opts.round)
			node.name = sprintf("%.2f", node.name)
		else
			node.name = (node.name.to_f*100).to_i.to_s
		end
	end
end

print tree.to_s