#!/usr/bin/env ruby

if (ARGV.size < 1)
   STDERR.printf("Usage: %s csv-file [csv-file...]\n", File.basename($0))
   exit(1)
end

csv, rest = ARGV

prefix = "/usr/local/depot/projects/GOS/antarctica/"
ARGV.each do |file|
  lib = File.basename(file).split(/.csv|.tab/).first
  if (!File.exist?(prefix + lib + ".fasta/apis"))
    STDERR.printf("Warning: %s not not exist\n", prefix + lib + ".fasta/apis")
    next
  end
  next if (File.exist?(prefix + lib + ".fasta/apis/apis.csv.bz2"))
  STDERR.printf("Copying %s...\n", file)
  system("cp #{file} #{prefix + lib + '.fasta/apis/apis.csv.bz2'}")
end
