#!/usr/bin/env ruby

if (ARGV.size != 2)
  STDERR << "Usage: " << File.basename($0) << " unique-classifications.txt taxonomy.txt\n"
  exit(1)
end

taxonomy, classification = ARGV

levels = ["superkingdom", "phylum", "class", "order", "family", "genus", "species"]


ids = Hash.new
parents = Hash.new

STDERR.printf("Loading taxonomy...\n")
File.new(taxonomy).each do |line|
  id, name, parent, rank = line.chomp.split("\t")
  key = name + "\t" + rank
  ids[key] = id.to_i
  parents[key] = parent.to_i
end
min_id = -10000 + ids.values.min

seen = Hash.new
STDERR.printf("Processing classification...\n")

printf("131567\tcellular organisms\t1\tno rank\n")
levels.size.times do |i|
  File.new(classification).each do |line|
    next if line =~/^kingdom/
    cl = line.chomp.split("\t")
    next if cl[i] == "Mixed" || cl[i] == "Undefined"
    key = cl[i] + "\t" + levels[i]
    if (!seen[key])
      if (ids[key])
        name, rank = key.split("\t")
        printf("%d\t%s\t%d\t%s\n", ids[key], name, parents[key], rank)
        seen[key] = true
      else
        if (i == 0)
          parent = 1
        else
          parent = ids[cl[i - 1] + "\t" + levels[i - 1]]
        end
        num = min_id
        min_id -= 1
        ids[key] = num
        parents[key] = parent
        seen[key] = true
        printf("%d\t%s\t%d\t%s\n", ids[key], cl[i], parents[key], levels[i])
      end
    end
  end
end