#!/usr/bin/env ruby

require 'optparse'
require 'ostruct'
require 'csv'
require 'ZFile'


opt = OpenStruct.new
opt.cluster = nil

o = OptionParser.new
o.banner << " csv [...csv]"
o.on("-c ", "--cluster-file ", String, "") {|c| opt.cluster = true}
begin
  o.parse!
rescue
  STDERR << $!.message << "\n"
  STDERR << o
  exit(1)
end
if (ARGV.size < 1)
  STDERR << o
  exit(1)
end

if (opt.cluster)
  cluster = Hash.new
  STDERR << "Loading clusters...\n"
  ZFile.new(opt.cluster).each do |line|
    pep, c1, c2 = line.chomp.split("\t")
    cluster[pep] = c1 + "|| " + c2
  end
else
  cluster = nil
end
p cluster.size
exit(1)

ARGV.each do |file|
  tab = File.basename(file).split(".csv").first + ".tab"
  out = File.new(tab, "w")
  CSV.foreach(file, :headers => true) do |line|
    meta = [line["Seq Name"], line["Dataset"], line["Annotation"], "APIS"]
    p meta
    exit(1)
  end
  out.close
end