#!/usr/bin/env ruby 

require 'rubygems'
require 'optimist'

ARGV.push("--help") if ARGV.empty?
opts = Optimist::options do
  banner File.basename($0)
  opt :input, "Input data file(s)", :required=>true, :type=>:strings
  opt :cmd, "command to run", :required=>true, :type=>:string
  opt :name, "name of job", :required=>true, :type=>:string
end

out = File.new(opts.name + ".com", "w")
out.printf("#!/usr/bin/env ruby\n")
out.printf("$VERBOSE = nil\n")
out.printf("data = %s\n", opts.input)
out.printf("num = ENV[\"SGE_TASK_ID\"].to_i - 1\n")
out.printf("system(\"%s \#{%s\}\")\n", opts.cmd, "data[num]", "data[num]")
out.close
File.chmod(0755, opts.name + ".com")
STDERR << "There are " << opts.input.size << " files...\n"
