#!/usr/bin/env ruby

require 'optparse'
require 'ostruct'
require 'csv'
require 'ZFile'


opt = OpenStruct.new
opt.hmm = nil

o = OptionParser.new
o.banner << " csv [...csv]"
o.on("-h ", "--hmm ", String, "HMM hits file") {|t| opt.hmm = t}
begin
  o.parse!
rescue
  STDERR << $!.message << "\n"
  STDERR << o
  exit(1)
end
if (ARGV.size < 1)
  STDERR << o
  exit(1)
end

if (opt.hmm)
  ZFile.new(opt.hmm).each do |line|
  end
end


ARGV.each do |file|
  tab = File.basename(file).split(".csv").first + ".tab"
  out = File.new(tab, "w")
  ZFile.new(file).each do |line|
    line = line.parse_csv
    sname, dataset, len, ann, tax, taxid, blastid, blastann, blaste, blastident, blastcov = line
    next if sname == "Seq Name"
    meta = [sname, dataset, ann, "APIS", go, gosrc, ec, ecsrc, hmm, blastid, blaste, blastident, blastcov, ""]
  end
  out.close
end