#!/usr/bin/env ruby 

require 'optimist'
require 'csv'
require 'axlsx'

ARGV.push("--help") if ARGV.empty?
opts = Optimist::options do
  banner File.basename($0)
  opt :input, "input csv/tab file(s)", :required=>true, :type=>:strings
  opt :expression, "regular expression to process file names", :type=>:string
  opt :output, "output file name", :required=>true, :type=>:string
  opt :tab, "use tab for separator rather than comma"
  opt :dropna, "Convert NA to empty field"
end

if opts.tab
  sep ="\t"
else
  sep = ","
end

def dropna(row)
  row.length.times do |i|
    row[i] = "" if row[i]=="NA"
  end
  row
end

proj = Axlsx::Package.new
wb = proj.workbook
opts.input.each do |file|
  if opts.expression && file =~/#{opts.expression}/
    name = $1
  else
    name = File.basename(file)
  end
  name = name[0..30]
  sheet = wb.add_worksheet(:name=> name)
  CSV.foreach(file, :col_sep=>sep) do |row|
    row = dropna(row) if opts.dropna
    sheet.add_row(row)
  end
end
proj.serialize(opts.output)
