#!/usr/bin/env ruby

require 'rubygems'
require 'bio'
require 'trollop'

ARGV.push("--help") if ARGV.empty?
opts = Trollop::options do
  banner File.basename($0)
  opt :input, "fasta file", :required=>true, :type=>:string
  opt :pattern, "pattern to match", :required=>true, :type=>:string
  opt :gaps, "ignore gaps"
  opt :highlight, "highlight matches in lower case"
  opt :verse, "show sequences not matching motif"
end

pat = opts.pattern.tr("NnX",".").upcase
if opts.gaps
  npat = ""
  pat.length.times do |i|
    npat += pat[i]+"-*"
  end
  pat = npat
end


pat.gsub!("V","[G|A|C]")
pat.gsub!("B","[G|T|C]")
pat.gsub!("H","[A|T|C]")
pat.gsub!("D","[G|A|T]")
pat.gsub!("K","[G|T]")
pat.gsub!("S","[G|C]")
pat.gsub!("W","[A|T]")
pat.gsub!("M","[A|C]")
pat.gsub!("Y","[C|T]")
pat.gsub!("R","[A|G]")

Bio::FlatFile.new(Bio::FastaFormat, File.new(opts.input)).each do |seq|
  s = seq.seq.upcase
  found = s.index(/(#{pat})/)
  if !found && opts.verse
    printf("%s\n", seq.entry_id)
  elsif found && !opts.verse
    if !opts.highlight
      printf("%s\t%s\t%d\n", seq.entry_id, $1, found+1)
    else
      print Bio::Sequence.new(s.gsub($1,$1.downcase)).to_fasta(seq.definition,60)
    end
  end
end
