#!/usr/bin/env ruby

require 'rubygems'
require 'uri'
require 'net/http'
require 'net/ftp'
require 'trollop'


ARGV.push("--help") if ARGV.empty?
opts = Trollop::options do
  banner File.basename($0)
  opt :input, "Existing list of genomic contigs (NC_***, etc.)", :required=>true, :type=>:string
end

contigs = Hash.new
File.new(opts.input).each do |line|
  contigs[name] = true
end

ftp = Net::FTP.new("ftp.ncbi.nlm.nih.gov")
ftp.login
ftp.chdir("/genomes/Bacteria")
STDERR.printf("Fetching ftp list...\n")
files = ftp.nlst("*_*")
STDERR.printf("Processing ftp list...\n")
files.each do |file|
  if (file =~/.gbk/)
    if (!contigs[File.basename(file, ".gbk")])
      STDERR.printf("Downloading %s\n", file)
      ftp.gettextfile(file)
    end
  end
end 
