#!/usr/bin/env ruby

require 'rubygems'
require 'optimist'
require 'Newick'
require 'fpdf'
require 'fcsv'

ARGV.push("--help") if ARGV.empty?

opts = Optimist::options do
  banner "Usage: " << File.basename($0) << " [options]"
  opt :csv, "apis flat file with tree", :required => true, :type => :string
  opt :sep, "separator for fields", :type=>:string, :default=>"\t"
  opt :headers, "file has header, use that", :default=>false
end

# function to generate seguid link to metarep for drawing tree
def segLink(entry)
  metalink = "http://www.jcvi.org/phylo-metarep/phylodb/seguid/"
  return metalink + entry.gsub(":","<>").gsub("/", "[]").gsub("+","()")
end

Dir.mkdir("tree") if !File.exist?("tree")
CSV.foreach(opts.csv, :col_sep=>opts.sep, :headers=>opts.headers) do |row|
	if opts.headers
		name, tree = row["Seq Name"], row["Tree"]
	else
  		name = row.first
  		tree = row.last
  	end
  if tree != "Tree" && !tree.nil?
  	tree = NewickTree.new(tree)
  	tree.draw("tree/" + name + ".pdf", boot="width", linker = :segLink)
  end
end
