#!/usr/bin/env ruby

require 'rubygems'
require 'mysql'
require 'optimist'

$VERBOSE=nil

ARGV.push("--help") if ARGV.empty?
opts = Optimist::options do
  banner File.basename($0)
  opt :database, "database name", :required=>true, :type=>:string
  opt :tables, "table(s) to output (if not all)", :type=>:strings
  opt :host, "database host", :required=>true, :type=>:string
  opt :user, "user", :default=>ENV["USER"], :type=>:string
  opt :password, "password", :required=>true, :type=>:string
  opt :where, "optional where conditional string to filter", :type=>:string
end

db = Mysql::new(opts.host, opts.user, opts.password, opts.database)

if opts.tables
  tables = opts.tables
else
  tables = []
  db.query("SHOW TABLES").each do |table|
    tables.push(table.first)
  end
end

tables.each do |table|
  out = File.new(table + ".txt", "w")
  query = "SELECT * FROM #{table}"
  query += " WHERE " + opts.where if (opts.where)
  db.query(query).each do |row|
    out.print row.join("\t") + "\n"
  end
  out.close
end

db.close
