#!/usr/bin/env ruby

require 'mysql'
require 'optparse'
require 'ostruct'
require 'csv'

opt = OpenStruct.new
opt.host = "mysql-lan-pro"
opt.user = ENV["USER"]
opt.password = ""



o = OptionParser.new
o.banner << " database-name [table]"
o.on("-h ", "--host ", String, "database host (#{opt.host})") {|t| opt.host = t}
o.on("-u ", "--user ", String, "database user (#{opt.user})") {|t| opt.user = t}
o.on("-p ", "--password ", String, "database password") {|t| opt.password = t}
begin
  o.parse!
rescue
  STDERR << $!.message << "\n"
  STDERR << o
  exit(1)
end
if (ARGV.size !=  1 && ARGV.size != 2)
  STDERR << o
  exit(1)
end

database, table = ARGV

db = Mysql::new(opt.host, opt.user, opt.password, database)

if (table)
  tables = [table]
else
  tables = []
  db.query("SHOW TABLES").each do |table|
    tables.push(table)
  end
end

tables.each do |table|
  out = File.new(table + ".txt", "w")
  db.query("SELECT * from #{table}").each do |row|
    out.print row.join("\t") + "\n"
  end
  out.close
end

db.close
