#!/usr/bin/env ruby

require 'rubygems'
require 'trollop'
require 'Newick'
require 'fpdf'
require 'csv'

ARGV.push("--help") if ARGV.empty?

opts = Trollop::options do
  banner "Usage: " << File.basename($0) << " [options]"
  opt :csv, "phylometarep formatted apis tab file", :required => true, :type => :string
end

# function to generate seguid link to metarep for drawing tree
def segLink(entry)
  metalink = "http://www.jcvi.org/phylo-metarep/phylodb/seguid/"
  return metalink + entry.gsub(":","<>").gsub("/", "[]").gsub("+","()")
end

Dir.mkdir("tree") if !Dir.exists?("tree")
CSV.foreach(opts.csv, :col_sep=>"\t") do |row|
  name = row.first
  tree = row.last
  tree = NewickTree.new(tree)
  tree.draw("tree/" + name + ".pdf", boot="width", linker = :segLink)
end