#!/usr/bin/env ruby

if (ARGV.size != 2)
  STDERR << "Usage: " << File.basename($0) << " kegg-list silva.tax\n"
  exit(1)
end

kegg, list = ARGV

abbr = Hash.new
File.new(kegg).each do |line|
  n, a, gs, species = line.chomp.split("\t")
  species, rest = species.split(" (")
  abbr[species] = a
end

match = Hash.new
match_abbr = Hash.new
match_len = Hash.new
File.new(list).each do |line|
  abbr.keys.each do |sp|
    if line=~/#{sp}/
      d, s, e = line.split(" ").first.split(".")
      len = (s.to_i - e.to_i).abs
      next if (len < 1600 || len > 2100)
      if (!match_len[sp] || match_len[sp] < len)
        next if match_len[sp].to_i > 1800
        match[sp] = line
        match_abbr[sp] = abbr[sp]
        match_len[sp] = len
      end
    end
  end
end

match.keys.each do |sp|
  print match_abbr[sp] + "\t" + match[sp]
end

