#!/usr/bin/perl

use strict;

foreach my $file (@ARGV) {
open IN,"<$file" or die "File $file not found error here\n";
my $out = $file;
$out =~ s/.fastq/.fa/;
open OUT, ">$out" or die "File $out cannot be created here\n";
my $c = 0;
my @line = ();
my $id ='';
my $seq = '';

my $processed = 0;

while(<IN>){
    chomp;
    $c++;
    if($c == 1){
        $processed++;
#        print STDERR "$processed reads processed\r";
        @line = split();
        $id = $line[0];
        $id =~ s/\@//;
        
    }elsif($c == 2){
        $seq = $_;
    }elsif($c == 4){
        $c = 0;
        print OUT ">$id\n$seq\n";
        $id ='';
        @line =();
        $seq ='';
    }else{}
}
close IN;
close OUT;
}
