#!/usr/bin/env ruby

if (ARGV.size != 1)
  STDERR.printf("usage: %s fasta-file\n", $0)
  exit(1)
end

fasta = ARGV.pop

seqs = Hash.new
name = nil
File.new(fasta).each {|line|
  line.chomp!
  line.tr!("*","")
  if (line =~ /^>/)
    name = line[1..line.length].split(";").pop
    seqs[name] = ""
  else
    seqs[name] += line
  end
}

lineLen = 60
printf("%d %d\n", seqs.size, seqs[name].length)
pos = 0
while (pos < seqs[name].length)
  seqs.keys.sort.each {|name|
    if (pos == 0)
      printf("%-10s ", name)
    end
    printf("%s\n", seqs[name][pos..pos + lineLen - 1])
  }
  pos += lineLen
  printf("\n")
end
