#!/usr/bin/env ruby

require 'optparse'
require 'rubygems'
require 'rsruby'
require 'bio'

ARGV.options {|opts|
  opts.banner << " fasta-file [fasta-file...]"
  begin
    opts.parse!
  rescue
    STDERR.puts $!.message
    STDERR.puts opts
    exit(1)
  end
  if (ARGV.size < 1)
    STDERR.puts opts
    exit(1)
  end
}


r = RSRuby.instance
ARGV.each {|fasta|
  name = fasta.split(".").first
  lens = []
  Bio::FlatFile.new(Bio::FastaFormat, File.new(fasta)).each {|seq|
    lens.push(seq.length)
  }
  r.pdf("#{name}_histo.pdf")
  r.hist(lens, :main => "Length distribution for #{name}", :xlab => "Length Bins")
  r.dev_off.call
}
