#!/usr/bin/env ruby

require 'bio'
require 'optimist'

ARGV.push("--help") if ARGV.empty?
opts = Optimist::options do
  banner File.basename($0)
  opt :input, "Input fasta file", :required=>true, :type=>:string
end

seqs = Hash.new
orfNum = "SID0000001"
aliFile = File.new(File.basename(opts.input, ".afa")+".ali", "w")
Bio::FlatFile.new(Bio::FastaFormat, File.new(opts.input)).each do |seq|
  seqs[orfNum] = seq.seq
  aliFile.printf("%s\t%s\n", orfNum, seq.definition)
  orfNum.succ!
end
aliFile.close

n = 0
slen = seqs.values.first.length
printf(" %d  %d\n", seqs.keys.length, slen)

while n <= slen
  print "\n" if n > 0
  seqs.keys.each do |name|
    sseq = seqs[name][n..n+59].gsub(/(.{10})/, '\1 ').strip
    name = " "*10 if n > 0
    printf("%s %s\n", name, sseq)
  end
  n += 60
end

