#!/usr/bin/env ruby

require 'rubygems'
require 'Phylogeny'

if (ARGV.size != 1)
  STDERR.printf("usage: %s fasta-file\n", $0)
  exit(1)
end

fasta, rest = ARGV

fasta2Stockholm(fasta.split(".").first + ".stock", fasta)
