#!/usr/bin/env ruby

require 'bio'
require 'ZFile'
require 'trollop'

ARGV.push("--help") if ARGV.empty?
opts = Trollop::options do
  banner File.basename($0)
  opt :input, "Input fasta file", :required=>true, :type=>:string
  opt :file, "Read patterns from file", :type=>:string
  opt :pattern, "pattern to match header", :type=>:string
  opt :fastq, "Read fastq format rather than fasta"
  opt :inverse, "Return things not matching"
end

if opts.fastq
  form = Bio::Fastq
else
  form = Bio::FastaFormat
end

if opts.file
  pattern = ""
  File.new(opts.file).each do |line|
    pattern += line.chomp+"|"
  end
  pattern.chop!
else
  pattern = opts.pattern
end

if !pattern
  STDERR << File.basename($0)+": Search pattern required\n"
  exit(1)
end

Bio::FlatFile.new(form, ZFile.new(opts.input)).each do |seq|
  if seq.definition =~/#{pattern}/
    print seq if !opts.inverse
  else
    print seq if opts.inverse
  end
end
