#!/usr/bin/env ruby

require 'rubygems'
require 'trollop'
require 'bio'    
require 'apis_lib'

ARGV.push("--help") if ARGV.empty?
opts = Trollop::options do
  banner File.basename($0)
  opt :input, "Input fasta file", :required=>true, :type=>:string
end

dna = isDNA?(opts.input)
fasta2Nexus(opts.input, dna)
