#!/usr/bin/env ruby

require 'rubygems'
require 'mysql'
require 'optimist'

ARGV.push("--help") if ARGV.empty?
opts = Optimist::options do
  banner File.basename($0)
  opt :input, "ids to retrieve data for", :type => :strings, :required=> true
  opt :file, "id(s) are files, not record ids"
  opt :contig, "use contig as search id"
  opt :database, "protein database", :default=>"phylodb", :type=>:string
  opt :everything, "return for all contigs"
  opt :species, "use species as search id"
  opt :seguid, "use seguid as search id"
  opt :name, "use (exact) sequence name as search id"
  opt :host, "database host", :default=>"mysql-lan-pro", :type=>:string
  opt :molecule, "return full DNA molecules"
  opt :rna, "return rRNAs, not proteins"
  opt :transcripts, "return transcripts, not proteins"
  opt :taxonid, "use taxon id as search"
  opt :desc, "include description field"
  opt :usename, "use name, not seguid as primary id"
  opt :taxonomy, "use taxonomy string as search"
end

if opts.file
  ids = []
  opts.input.each do |file|
    File.new(file).each do |line|
      ids.push(line.split(" ").first)
    end
  end
else
  ids = opts.input
end

db = Mysql.new(opts.host, "access", "access", opts.database)

# quotes single quotes, etc. for SQL usage
class String
  # quotes single quotes, etc. for SQL usage
  def quote
    return self.gsub(/\\/, '\&\&').gsub(/'/, "''")
  end
  # formats string as fasta record
  def to_fasta(header, len = 60)
    return ">#{header}\n#{self.gsub("*","").gsub(Regexp.new(".{1,#{len}}"), "\\0\n")}"
  end
end

def flag_string(flag_num)
  flag_num = flag_num.to_i
  if flag_num == 1 || flag_num == 2
    "kegg"
  elsif flag_num == 5
    "chloro"
  elsif flag_num == 6
    "mito"
  elsif flag_num == 7
   "transcript"
  else
    "rest"
  end
end

if opts.taxonomy
  newids = []
  db.query("SELECT DISTINCT taxon_id, taxonomy FROM contigs").each do |row|
    tid, tax = row
    ids.each do |id|
      if tax.index(opts.taxonomy)
        newids.push(tid)
      end
    end
  end
  ids = newids.uniq
end

if opts.transcripts
  query = "SELECT p.seguid, p.name, t.seq, annotation, species, strain, c.taxon_id, p.protein_flag, description FROM proteins AS p, contigs as c, transcripts as t WHERE c.name = p.contig_name AND t.name = p.name "
elsif opts.rna
  query = "SELECT r.name, r.name, r.seq, annotation, species, strain, c.taxon_id, description FROM rrnas AS r, contigs AS c WHERE c.name = r.contig_name "
elsif opts.molecule
  query = "SELECT name, name, seq, form, species, strain, taxon_id, contig_flag, description FROM contigs AS c WHERE c.name = c.name "
elsif opts.seguid
  query = "SELECT p.seguid, p.name, p.seq, annotation, species, strain, c.taxon_id, p.protein_flag, description FROM proteins AS p, contigs AS c WHERE c.name = p.contig_name "
else
  query = "SELECT p.seguid, p.name, p.seq, annotation, species, strain, c.taxon_id, p.protein_flag, description FROM proteins AS p, contigs AS c WHERE c.name = p.contig_name "
end

while !ids.empty?
  q = query.dup
  iset = ids.pop(10000)
  inList = "('" + iset.join("','") + "')"
  if opts.species
    q += "AND species IN #{inList}"
  elsif opts.seguid
    q += "AND seguid IN #{inList}"
  elsif opts.contig
    q += "AND c.name IN #{inList}"
  elsif opts.taxonid || opts.taxonomy
    q += "AND c.taxon_id IN #{inList}"
  else
    q += "AND p.name IN #{inList}"
  end

  db.close
  db = Mysql.new(opts.host, "access", "access", opts.database)
  db.query(q).each do |row|
    seguid, seq_name, seq, ann, species, strain, taxon_id, flag, desc = row
    species += " " + strain if strain.to_s != "" && !species.include?(strain.to_s)
    header = seguid + " " + seq_name + " \<\<" + ann.to_s + "\>\> {" + species + "} " + taxon_id.to_s
    header = seq_name + " \<\<" + ann.to_s + "\>\> {" + species + \
"} " + taxon_id.to_s if opts.usename
    header += " " + desc if opts.desc
    header += " " + flag_string(flag) if flag
    begin
      print seq.to_fasta(header, 60)
    rescue
      STDERR << "No sequence for " << seq_name << ". Skipping...\n"
    end
  end
end




