#!/usr/bin/env ruby

require 'ostruct'
require 'optparse'
require 'rubygems'
require'bio'
include Bio
opt = OpenStruct.new

ARGV.options {|opts|
  opts.banner << " cluster-list"
  #opts.on(nil, "--report", "run apisReport when done") {|t| opt.report = t}    
  begin
    opts.parse!
  rescue
    STDERR.puts $!.message
    STDERR.puts opts
    exit(1)
  end
  if (ARGV.size != 1)
    STDERR.puts opts
    exit(1)
  end
}

list, rest = ARGV

File.new(list).each {|line|
  name = line.split(".dfa").first.gsub("\"","")
  pseq = nil
  FlatFile.new(FastaFormat, File.new(name + ".afa")).each {|seq|
    pseq = seq if (pseq.nil?)
    pseq = seq if (seq.entry_id =~/GSU/)
  }
  print pseq
}
