#!/usr/bin/env ruby

require 'trollop'
require 'bio'
require 'ZFile'


ARGV.push("--help") if ARGV.empty?
opts = Trollop::options do
  banner File.basename($0)
  opt :input, "name of filter to filter", :required=>true, :type=>:string
  opt :format, "type of seq", :default=>"fasta"
  opt :minv, "minimum length", :type=>:integer, :required=>true
  opt :maxv, "maximum length", :type=>:integer, :required=>true
end


if opts.format == "fasta"
  format = Bio::FastaFormat
elsif opts.format == "fastq"
  format = Bio::Fastq
else
  format = "???"
end

Bio::FlatFile.new(format, ZFile.new(opts.input)).each do |seq|
  print seq if seq.seq.length >= opts.minv && seq.seq.length <= opts.maxv
end
