#!/usr/bin/env ruby

require 'rubygems'
require 'bio'
require 'ZFile'

if (ARGV.size != 3)
  STDERR.printf("usage: %s seq.fasta min max\n", $0)
  exit(1)
end

file, min, max = ARGV
min = min.to_i
max = max.to_i

seqs = Hash.new

Bio::FlatFile.new(Bio::FastaFormat, ZFile.new(file)).each {|seq|
  print seq if (seq.length >= min && seq.length <= max)
}
