#!/usr/bin/env ruby

require 'optparse'
require 'ostruct'
require 'bio'

opt = OpenStruct.new
o = OptionParser.new
o.banner << " dna-file tab-file"
begin
  o.parse!
rescue
  STDERR << $!.message << "\n"
  STDERR << o
  exit(1)
end
if (ARGV.size != 2)
  STDERR << o
  exit(1)
end

dna, tab = ARGV
gc = Hash.new

Bio::FlatFile.new(Bio::FastaFormat, File.new(dna)).each do |seq|
  gc[seq.entry_id] = seq.seq.count("GCgc")*100/seq.length
end

hits = Hash.new
percents = Hash.new

File.new(tab).each do |line|
  read, hit, percent, length = line.chomp.split("\t")
  percent = percent.to_f
  length = length.to_i
  next if length < 100
  if (hits[read].nil? || percents[read] < percent)
    percents[read] = percent
    hits[read] = line
  end
end

hits.keys.each do |read|
  next if hits[read] =~/Bacteriovorax/
  
  if ((percents[read] > 95 && hits[read] =~/326423644|326424156/) || (percents[read] > 70 && hits[read] =~/888/))
    print hits[read]
  end
end
