#!/usr/bin/env ruby

require 'GeneExpression'
require 'rubygems'
require 'csv'


if (ARGV.size < 2)
  STDERR.printf("usage: %s csv threshold\n", $0)
  exit(1)
end

csv, threshold = ARGV
threshold = threshold.to_f


STDERR << "Loading Spreadsheet...\n"
table = csv.read(csv, {:headers => true, :converters => :numeric})

STDERR << "Calculating R values...\n"
total = Hash.new
table.headers.each do |col|
  next if (col == "Contigs" || col == "Isogroup" || col == "Gene")
  break if (col == "Sum")
  total[col] = table[col].last
end

if (!table.headers.include?("R"))
  print (table.headers.push("R")).to_csv
else
  print table.headers.to_csv
end

table.each do |row|
  if (!row["Gene"].nil? || !row["Contigs"].nil?)
    row["R"] = (100*rvalue(total, row)).to_i/100.0
    next if (row["R"] < threshold)
  end
  print row.to_csv
end