#!/usr/bin/env ruby

require 'optparse'

ARGV.options {|opts|
  opts.banner << " dir [dir...]"
  begin
    opts.parse!
  rescue
    STDERR.puts $!.message
    STDERR.puts opts
    exit(1)
  end
  if (ARGV.size < 1)
    STDERR.puts opts
    exit(1)
  end
}

ARGV.each {|dir|
  if File.directory?(dir)
    if (Dir.glob(dir + "/*.html").empty?)
      if (Dir.glob(dir + "/PEP*.pep").empty?)
	if !(Dir.glob(dir + "/trees/*.tree").empty?)
	  p dir
	end
      end
    end
  end
}
