#!/usr/bin/env ruby

require 'GeneExpression'
require 'csv'


if (ARGV.size < 2)
  STDERR.printf("usage: %s csv threshold\n", $0)
  exit(1)
end

csv, threshold = ARGV
threshold = threshold.to_f


STDERR << "Loading Spreadsheet...\n"
table = CSV.read(csv, {:headers => true, :converters => :numeric})

STDERR << "Calculating R values...\n"
totals = []
i = 0
categories = []
table.headers.each do |col|
  next if (col == "Contigs" || col == "Isogroup" || col == "Gene")
  break if (col == "Sum")
  totals[i] = table[col].last
  categories.push(col)
  i += 1
end


if (!table.headers.include?("R"))
  print (table.headers.push("R")).to_csv
else
  print table.headers.to_csv
end

table.each do |row|
  if (!row["Gene"].nil? || !row["Contigs"].nil?)
    counts = categories.collect {|x| row[x]}
    row["R"] = GeneExpression.rvalue(totals, counts)
    next if (row["R"] < threshold)
  end
  print row.to_csv
end