#!/usr/bin/env ruby

Dir.glob("*").each {|dir|
  if (File.directory?(dir))
    p = Dir.glob("#{dir}/*.pep").first
    File.new(p).each {|line|
      if line =~/\{([^\}]*)/
	sp = $1.tr(" ","_")
	system("mv #{dir} #{sp}")
      end
      break
    }
  end
}
