#!/usr/bin/env ruby

require 'optparse'

ARGV.options {|opts|
  opts.banner << " att-file taxonfix.list"
  begin
    opts.parse!
  rescue
    STDERR.puts $!.message
    STDERR.puts opts
    exit(1)
  end
  if (ARGV.size != 2)
    STDERR.puts opts
    exit(1)
  end
}

att, fix = ARGV

fnames = ["name", "size", "species", "strain", "taxon_id", "taxonomy", "form",  
    "proteins", "rrnas", "trnas",  "gc"]

info = Hash.new
File.new(att).each {|line|
  fields = line.chomp.split("\t")
  name = fields.first
  info[name] = Hash.new
  fnames.each {|fname|
    info[name][fname] = fields.shift
  }
}

File.new(fix).each {|line|
  fields = line.chomp.split("\t")
  name = fields.first
  fields.each {|field|
    if field.index("=>")
      fname, value = field.split("=>")
      info[name][fname] = value
    end
  }
}


info.keys.sort.each {|key|
  fnames.each {|field|
    printf("%s\t", info[key][field])
  }
  printf("\n")
}
