#!/usr/bin/env ruby 

require 'optimist'
require 'bio'
require 'csv'

ARGV.push("--help") if ARGV.empty?
opts = Optimist::options do
  banner File.basename($0)
  opt :email, "email address", :default=>"jbadger@jcvi.org"
  opt :name, "search name", :default=>"Badger JH"
  opt :years, "years to include", :required=>true, :type=>:integers
end

Bio::NCBI.default_email=opts.email

query = opts.name+"[au] AND ("
opts.years.each do |year|
  query += year.to_s + "[dp] OR "
end
query = query[0..query.length - 5] + ")"
pmeds = Bio::PubMed.esearch(query)

names = Hash.new
lname = nil
Bio::PubMed::efetch(pmeds).each do |record|
  record.split("\n").each do |line|
    if line =~/^AU/
      head, sname = line.split("- ", 2)
      names[lname] = sname
    elsif line=~/^FAU /
      head, name = line.split("- ", 2)
      lname = name.split(",", 2).join("\t")
      names[lname] = ""
    end
  end
end

print ["Last Name", "First Name", "Short Name", "Institution", "Conflict Type"].to_csv
names.keys.sort.each do |name|
  row = name.split("\t")
  row += [names[name]]
  row += [""]
  row += ["Collaborator"]
  print row.to_csv
end
