#!/usr/bin/env ruby

require 'rubygems'
require 'bio'    
require 'trollop'

ARGV.push("--help") if ARGV.empty?
opts = Trollop::options do
  banner File.basename($0)
  opt :input, "Input afa files", :required=>true, :type=>:strings
end

peps = Hash.new
opts.input.each do |file|
  Bio::FlatFile.new(Bio::FastaFormat, File.new(file)).each do |seq|
    peps[seq.entry_id] = Hash.new if !peps[seq.entry_id]
    peps[seq.entry_id][file] = seq.seq
  end
end

peps.keys.sort.each do |sp|
  printf(">%s\n",sp)
  peps[sp].keys.sort.each do |pep|
    print peps[sp][pep].seq
  end
  printf("\n")
end
