#!/usr/bin/env ruby

require 'ostruct'
require 'optparse'
opt = OpenStruct.new

opt.tax = "phylum"
levels = ["kingdom", "phylum", "class", "order", "family", "genus"]

ARGV.options {|opts|
  opts.banner << " gene-list apis-dir"
  opts.on("-l ", "--level ", "taxonomic level (default #{opt.tax})") {|t| opt.tax = t}    
  begin
    opts.parse!
  rescue
    STDERR.puts $!.message
    STDERR.puts opts
    exit(1)
  end
  if (ARGV.size != 2)
    STDERR.puts opts
    exit(1)
  end
}

opt.tax.downcase!
if (!levels.include?(opt.tax))
  STDERR.printf("tax levels must be one of: kingdom, phylum, class, order, family, genus\n")
  exit(1)
else
  taxNum = levels.index(opt.tax)
end


list, dir = ARGV

File.new(list).each {|line|
  id, rest = line.split(" ")
  begin
    name = Dir.glob(dir + "/neighbors/*" + id + "*")
    info = File.read(name.first)
    fields = info.split("\n").first.split("\t")
    printf("%s\t%s\n", id, fields[taxNum])
  rescue
    STDERR.printf("Skipping %s -- not found\n", id)
  end
}
