#!/usr/bin/env ruby 

require 'rubygems'
require 'ZFile'
require 'trollop'
require 'fastercsv'

ARGV.push("--help") if ARGV.empty?
opts = Trollop::options do
  banner File.basename($0)
  opt :col, "column to use", :required=>true, :type=>:integer
  opt :csv, "Parse using csv library"
  opt :delimiter, "delimter character", :default=>" ", :type=>:string
  opt :file, "use file rather than STDIN", :type => :string
  opt :redundant, "Include redundant values", :default=>false
end

if opts.file
  inFile = ZFile.new(opts.file)
else
  inFile = STDIN
end

if (opts.csv)
  iter=FasterCSV.new(inFile)
else
  iter = inFile
end

seen = Hash.new

iter.each do |row|
  row = row.chomp.split(opts.delimiter) if !opts.csv
  field = row[opts.col]
  print field + "\n" if !field.nil? && (opts.redundant || !seen[field])
  seen[field] = true
end




