#!/usr/bin/env ruby

require 'optparse'
require 'ostruct'

opt = OpenStruct.new
o = OptionParser.new
o.banner << " gff-file"
o.on("-v", "--verbose", "Run verbosely") {opt.verbose = true}
begin
  o.parse!
rescue
  STDERR << $!.message << "\n"
  STDERR << o
  exit(1)
end
if (ARGV.size != 1)
  STDERR << o
  exit(1)
end

gentran = 500000

gff = ARGV.first


geneId = nil
transcriptId = nil
File.new(gff).each do |line|
  seqname, source, feature, start, stop, score, strand, frame, attribute = line.chomp.split("\t")
  if feature =~/gene|exon/
    row = [seqname, source, feature, start, stop, score, strand, frame]
    geneId = nil
    if (attribute =~/name ([^;]*)[;|\_]/)
      geneId = $1
    end
    if (attribute =~/transcriptId ([0-9|\_|a-z|A-Z|\+|\-]*)/)
      transcriptId = $1
    end
    if source == "GenBank"
      row[2] = "exon" if row[2] == "gene"
      transcriptId = gentran
      geneId = gentran
      gentran = gentran + 1
    end
    geneId = transcriptId if (!geneId)
    row.push("gene_id \"#{geneId}\"; transcript_id \"#{transcriptId}\";")
    print row.join("\t") + "\n"
  end
end
