#!/usr/bin/env ruby


ARGV.each {|pep1|
  ARGV.each {|pep2|
    next if pep1 == pep2
    vs = pep1 + "_vs_" + pep2
    rvs = pep2 + "_vs_" + pep1
    if (!File.exists?(vs + ".recip"))
      cmd = "cd #{Dir.pwd};bestRecip #{vs}.blastp #{rvs}.blastp"
      system("qsub -P 215011 -e err.log -o #{vs}.recip '#{cmd}'")
    end
  }
}
