#!/usr/bin/env ruby

if (ARGV.size != 1)
  STDERR.printf("usage: %s hmmer-file\n", $0)
  exit(1)
end

file = ARGV.shift
species = Hash.new
start = false
seqs = Hash.new
File.new(file).each {|line|
  if (line =~ /^#|\/\//)
    start = true
    next
  end
  next if !start
  name, ali = line.split(" ")
  next if (!start || ali.nil?)
  ali.gsub!(".","-")
  seqs[name] = "" if (seqs[name].nil?)
  seqs[name] += ali += "\n"
}

seqs.keys.each {|name|
  printf(">%s\n%s",name,seqs[name])
}
