#!/usr/bin/env ruby

species = Hash.new
start = false
seqs = Hash.new
STDIN.each {|line|
  if (line =~ /^#|\/\//)
    start = true
    next
  end
  next if !start
  name, ali = line.split(" ")
  next if (!start || ali.nil?)
  ali.gsub!(".","-")
  seqs[name] = "" if (seqs[name].nil?)
  seqs[name] += ali += "\n"
}

seqs.keys.each {|name|
  printf(">%s\n%s",name,seqs[name])
}
