#!/usr/bin/env ruby

require 'trollop'
require 'ZFile'
require 'Set'

ARGV.push("--help") if ARGV.empty?
opts = Trollop::options do
  banner File.basename($0)
  opt :input, "input directory", :required=>true, :type=>:string
end

excluded = [1, 2, 131567, 9606]
counts = Hash.new
names = Set.new

Dir.glob(opts.input+"/*.kraken*").each do |file|
  name = File.basename(file).split("_gdc").first
  names.add name
  ZFile.new(file).each do |line|
    _,_,tid = line.chomp.split("\t")
    tid = tid.to_i
    if !excluded.include? tid
      counts[tid] = Hash.new if !counts[tid]
      counts[tid][name] = 0 if !counts[tid][name]
      counts[tid][name] += 1
    end
  end
end

names = names.to_a.sort
print (["TID"] + names).join(",")+"\n"
counts.keys.sort.each do |tid|
  line = []
  line.push(tid)
  names.each do |name|
    line.push counts[tid][name]
  end
  print line.join(",")+"\n"
end
