#!/usr/bin/env ruby

require 'trollop'

ARGV.push("--help") if ARGV.empty?
opts = Trollop::options do
  banner File.basename($0)
  opt :input, "input file(s)", :required=>true, :type=>:strings
  opt :exclude, "exclude taxon", :type=>:string
end

counts = Hash.new
total = Hash.new

opts.input.each do |file|
  File.new(file).each do |line|
    x, tax = line.chomp.split("\t")
    if !opts.exclude || tax !~ /#{opts.exclude}/
      counts[tax] = Hash.new if !counts[tax]
      counts[tax][file] = 0 if !counts[tax][file]
      total[tax] = 0 if !total[tax]
      counts[tax][file] += 1
      total[tax] += 1
    end
  end
end

otuTable = File.new("otu.txt","w")
taxTable = File.new("tax.txt", "w")

otu = "OTU_0001"

otuTable.print (["#OTU"] + opts.input.collect{|x|
                  x.split(".")[0]}).join("\t")+"\n"
taxTable.print ["#OTU", "taxonomy"].join("\t")+"\n"

total.keys.sort {|x,y| total[y] <=> total[x]}.each do |tax|
  c = opts.input.collect{|x| counts[tax][x].to_i}
  otuTable.print ([otu] + c).join("\t")+"\n"
  taxTable.print [otu, tax].join("\t")+"\n"
  otu.succ!
end

otuTable.close
taxTable.close
