#!/usr/bin/env ruby

require 'ostruct'
require 'optparse'
opt = OpenStruct.new

ARGV.options {|opts|
  opts.banner << " tax.txt tree-info"
  #opts.on(nil, "--report", "run apisReport when done") {|t| opt.report = t}    
  begin
    opts.parse!
  rescue
    STDERR.puts $!.message
    STDERR.puts opts
    exit(1)
  end
  if (ARGV.size != 2)
    STDERR.puts opts
    exit(1)
  end
}

tax, info = ARGV

tx = Hash.new
File.new(tax).each do |line|
  fields = line.chomp.split("\t")
  tx[fields.first] = fields.last
end

File.new(info).each do |line|
  fields = line.chomp.split("\t")
  if (fields[2] == "r")
    fields.each do |field|
      print field + "\t"
    end
    print tx[fields.last] if (tx[fields.last])
    printf("\n")
  else
    print line
  end
end
