#!/usr/bin/env ruby

require 'rubygems'
require 'active_record'
require 'rubygems'
require'bio'
require 'MySQL'

db = MySQL.new
fasta = ARGV.shift

Bio::FlatFile.new(Bio::FastaFormat, File.new(fasta)).each {|seq|
  if seq.definition =~/\[EC:([^\]]*)\]/
    prot = Ecprotein.new
    prot.name = seq.entry_id.tr(":","_")
    prot.ec_number = $1
    prot.seq = seq.seq
    prot.annotation = seq.definition.split(" ",2).last.split(" [").first
    prot.save
  end
}
