#!/usr/bin/env ruby

require 'LogDet'
require 'Phylogeny'
require 'Newick'

estimateDist = true
if (ARGV.index("-nodist"))
  ARGV.delete("-nodist")
  estimateDist = false
end

if (ARGV.size !=1 && ARGV.size != 2)
  STDERR.printf("usage: %s [-nodist] fasta-file [outgroup]\n", $0)
  exit(1)
end

fasta, outgroup = ARGV

lg = LogDet.new(fasta)
begin
  tree = lg.phylipNJ(100, outgroup)
  if (estimateDist)
    tree = estimateMLBranchLengths(tree, fasta)
    tree.midpointRoot if (outgroup.nil?)
  end
  print tree.to_s + "\n"
rescue
  STDERR.printf("Problem %s inferring tree\n", $!)
end
