#!/usr/bin/env ruby

require 'optparse'
require 'ostruct'
require 'rubygems'
require 'bio'

#For testing in TextMate:
#Dir.chdir("/Users/jbadger/work/hmp")
#ARGV.push("Airways_all_trim.afa")

colors = {"Bacteria; Firmicutes" =>"red", 
  "Bacteria; Bacteroidetes" => "green", "Bacteria; Proteobacteria" => "lightgrey",
  "Bacteria; Verrucomicrobia" => "purple", 
  "Bacteria; Lentisphaerae" => "orange", 
  "Bacteria; Actinobacteria" => "yellow",
  "Bacteria; Fusobacteria" => "pink", "Bacteria; Spirochaetes" => "brown",
  "Archaea; Euryarchaeota" => "cyan", "Bacteria; Chlamydiae" => "darkgrey",
  "Bacteria; Tenericutes" => "lightgreen", "Bacteria; Cyanobacteria" => "darkgreen",
  "Bacteria; Acidobacteria" => "lavender"}

def generateRandomColor(mix) 
  red = rand(256)
  green = rand(256)
  blue = rand(256)
  red = (red + mix[0]) / 2
  green = (green + mix[1]) / 2
  blue = (blue + mix[2]) / 2
  color = "#" + red.to_s(base=16) + green.to_s(base=16) + blue.to_s(base=16)
  return color.upcase
end
  
opt = OpenStruct.new
o = OptionParser.new
o.banner << " alignment.afa [alignment.afa...]"
begin
  o.parse!
rescue
  STDERR << $!.message << "\n"
  STDERR << o
  exit(1)
end
if (ARGV.size < 1)
  STDERR << o
  exit(1)
end

ARGV.each {|afa|
  taxinfo = Hash.new
  fullNames = Hash.new
  Bio::FlatFile.new(Bio::FastaFormat, File.new(afa)).each {|seq|
    fullNames[seq.entry_id] = seq.definition.split(" ")[0] + "_" + seq.definition.split(" ")[1].to_s + "_" + seq.definition.split(" ")[2].to_s
    if (seq.definition =~/;/)
      tax = seq.definition.split(" ")[1].split(";")
      taxinfo[seq.entry_id] = tax[0] + "; " + tax[1]
      if (!colors[taxinfo[seq.entry_id]])
        colors[taxinfo[seq.entry_id]] = generateRandomColor([255,255,255])
      end
    end
  }
  name = File.basename(afa, ".afa")
  tree = name + ".tree"
  if (!File.exists?(tree))
    system("FastTree -nt -gtr  < #{afa} > #{tree}")
  end
  reroot = name + "_rooted.tree"
  if (!File.exist?(reroot))
    STDERR << "Rerooting #{tree}...\n"
    system("newickReroot #{tree} > #{reroot}")
  end
  infotmp = name + ".info.tmp"
  system("treeinfo.pl #{reroot} > #{infotmp}")
  info = name + ".info"
  infof = File.new(info, "w")
  File.new(infotmp).each {|line|
    fields = line.split(" ", 4)
    num, dist, type, sp = line.chomp.split("\t")
    if (type == "r")
      if (taxinfo[sp])
        line = num + "\t" + dist + "\t" + type + "\t" + sp + "\t" + taxinfo[sp] + "\n"
      else
        line = num + "\t" + dist + "\t" + "q" + "\t" + fullNames[sp] + "\n"
      end
    end
    infof.print line
  }
  infof.printf("ttclr\tq\torange\tblue\n")
  colors.keys.each {|key|
    infof.printf("htax\t%s\t%s\n", key, colors[key])
  }
  infof.close
  File.unlink(infotmp)
  svgtmp = name + ".svgtmp"
  system("treeinfo2svg.pl #{info} > #{svgtmp}")
  svg = name + ".svg"
  svgf = File.new(svg, "w")
  y = -150
  File.new(svgtmp).each {|line|
    if line =~/<\/svg>/
      colors.keys.each {|key|
        y += 210
        svgf.printf("<rect x=\"100\" y=\"#{y}\" width=\"6000\"  height=\"300\" fill=\"#{colors[key]}\"/>
        <text x=\"100\" y=\"#{y+200}\" font-size=\"290\" font-weight=\"bold\" font-family=\"Verdana\" fill=\"black\">#{key}</text>\n")
      }
    else
      svgf.print line
    end
  }
  svgf.printf("<text x=\"7300\" y=\"700\" font-size=\"500\" font-weight=\"bold\" font-family=\"Verdana\" 
  fill=\"black\">#{name}</text>")
  svgf.printf("</svg>\n")
  svgf.close
  File.unlink(svgtmp)
  pdf = name + ".pdf"
  system("svg2pdf  #{svg} > #{pdf}")
}