#!/usr/bin/env ruby

require 'optimist'

ARGV.push("--help") if ARGV.empty?
opts = Optimist::options do
  banner File.basename($0)
  opt :input, "input file", :required=>true, :type=>:string
end

headers = nil
print ["Var_label","Var_type"].join("\t")+"\n"
File.new(opts.input).each do |line|
  fields = line.chomp.split("\t")
  if headers.nil?
    headers = fields
    0.upto(headers.length - 1) do |i|
      if i == 0
        type = "Sample"
      else
        type = "discrete"
      end
      print [headers[i], type].join("\t")+"\n"
    end
  end
end
