#!/usr/bin/env ruby

require 'rubygems'
require 'trollop'

ARGV.push("--help") if ARGV.empty?
opts = Trollop::options do
  banner File.basename($0)
  opt :input, "reads to map", :required=>true, :type=>:strings
  opt :reference, "reference to map to", :required=>true, :type=>:string
end

bwa = `which bwa`.chomp

while(!opts.input.empty?)
  r1 = opts.input.shift
  r2 = opts.input.shift
  s1 = r1+"_"+File.basename(opts.reference)+".sai"
  s2 = r2+"_"+File.basename(opts.reference)+".sai"
  sam = r1+".sam"
  if !File.exists?(s1)
    system("#{bwa} aln #{opts.reference} #{r1} > #{s1}")
  end
  if !File.exists?(s2)
    system("#{bwa} aln #{opts.reference} #{r2} > #{s2}")
  end
  if !File.exists?(sam)
    system("#{bwa} sampe #{opts.reference} #{s1} #{s2} #{r1} #{r2} > #{sam}")
  end
end
