#!/usr/bin/env ruby 

require 'trollop'
require 'ZFile'

ARGV.push("--help") if ARGV.empty?
opts = Trollop::options do
  banner File.basename($0)
  opt :alias, "alias file", :type=>:string
  opt :input, "blast M8 file", :required=>true, :type=>:string
  opt :fasta, "fasta file", :required=>true, :type=>:string
  opt :mcl, "run mcl after processing"
  opt :threshold, "blast threshold", :type=>:float, :default=>1.0
end

if opts.ali
  ali = Hash.new
  File.new(opts.alias).each do |line|
    num, tax, abbr = line.chomp.split("\t")
    ali[num.to_i] = abbr
  end
end

STDERR << "Processing Fasta...\n"
species = Hash.new

ZFile.new(opts.fasta).each do |line|
  if line =~/^>([^\s]*)/
    name = $1
    species[name] = []
    num = line.split(" ")[-2].to_i
    if opts.ali
      if ali[num]      
        species[name].push(ali[num])
      else
        STDERR << "Missing alias for " << seq.definition << "\n"
        exit(1)
      end
    else
      species[name] = [name]
    end
  end
end

scores = Hash.new
maxScore = Hash.new
STDERR << "Processing Blast...\n"
ZFile.new(opts.input).each do |line|
  fields = line.chomp.split("\t")
  q = fields[0]
  s = fields[1]
  score = fields[11]
  evalue = fields[10].to_f
  if score && evalue <= opts.threshold
    score = score.to_f
    scores[q] = Hash.new if !scores[q]
    scores[q][s] = score if !scores[q][s] || score > scores[q][s]
    if !maxScore[q] || maxScore[q] < score
      maxScore[q] = score
    end
  end
end

STDERR << "Writing Matrix...\n"
mcl = File.basename(opts.input).split(".m8").first + ".mcl"
out = File.new(mcl, "w") 
scores.keys.each do |q|
  species[q].each do |qsp|
    scores[q].keys.each do |s|
      species[s].each do |ssp|
        ratio = scores[q][s]/maxScore[q]
        if opts.ali
          out.printf("%s|%s\t%s|%s\t%8.4f\n", qsp, q, ssp, s, ratio)
        else
          out.printf("%s\t%s\t%8.4f\n", q, s, ratio)
        end
      end
    end
  end
end
out.close

if opts.mcl
  STDERR << "Running clustering...\n"
  clusters = File.basename(mcl, ".mcl") + ".clusters"
  system("mcl #{mcl} --abc -o #{clusters}")
end
