#!/usr/bin/env ruby

require 'rubygems'
require 'csv'

headers1 = []
sanger = Hash.new
CSV.foreach("/Users/jbadger/Dropbox/Public/sum.csv") do |row|
  if (headers1.empty?)
		headers1 = row
	else
	  sanger[row.first] = row if row[7].to_i > 1
  end
end

headers2 = []
pyro = Hash.new
File.new("/Users/jbadger/Dropbox/Public/yuzhenLQToAllBadgerTopHitsWith454Descriptions.txt").each do |line|
  row = line.chomp.split("\t")
  if (headers2.empty?)
		headers2 = row
	else
	  percent = row[3].to_f
	  if (pyro[row[1]])
	    oldPercent = pyro[row[1]][3].to_f
    else
      oldPercent = 0
    end
	  if (pyro[row[1]].nil? ||  oldPercent < percent)
	    pyro[row[1]] = row if (percent > 95)
    end
  end
end

print (headers1 + headers2).to_csv
sanger.keys.sort {|x, y| sanger[y][5].to_f <=> sanger[x][5].to_f}.each do |key|
  row = sanger[key]
  row += pyro[key] if pyro[key]
  print row.to_csv
end
