#!/usr/bin/env ruby

require 'uri'
require 'net/http'
require 'net/ftp'
require 'rubygems'
require 'bio'
require 'httpclient'
require 'csv'

def getTaxId(species)
  link = "http://www.ncbi.nlm.nih.gov"
  link += "/sites/entrez?db=Taxonomy&cmd=search&term="
  clnt = HTTPClient.new
  species = species.gsub(" ","%20")
  num = 0
  clnt.get(link + species).body.content.split("\n").each do |line|
    if (line =~/wwwtax.cgi\?id=([0-9]+)/)
      num = $1
    end
  end
  return num.to_i
end

if (ARGV.size == 0)
  STDERR.printf("Usage: %s fasta|csv [...fasta|csv]\n", File.basename($0))
  exit(1)
end

need = []
ARGV.each do |file|
  if (file =~/.csv/)
    CSV.foreach(file) do |row|
      need.push(row[0])
    end
  else
    Bio::FlatFile.new(Bio::FastaFormat, File.new(file)).each do |seq|
      if (seq.definition =~/\{([A-Z|a-z|0-9|\ |\.]*)\}/)
        need.push($1)
      end
    end
  end
end

need.each do |sp|
  tx = getTaxId(sp)
  if (sp.nil?)
    STDERR.printf("No Tax Id for %s\n", sp)
  else
    printf("%s\t%d\n", sp, tx)
  end
end