#!/usr/bin/env ruby

require 'uri'
require 'net/http'
require 'net/ftp'
require 'rubygems'
require 'rubygems'
require 'bio'
require 'httpclient'


def getTaxId(species)
  link = "http://www.ncbi.nlm.nih.gov"
  link += "/sites/entrez?db=Taxonomy&cmd=search&term="
  clnt = HTTPClient.new
  species = species.gsub(" ","%20")
  num = 0
  clnt.get(link + species).body.content.split("\n").each {|line|
    if (line =~/wwwtax.cgi\?id=([0-9]+)/)
      num = $1
    end
  }
  return num.to_i
end

if (ARGV.size == 0)
  STDERR.printf("Usage: %s fasta [...fasta]\n", File.basename($0))
  exit(1)
end

ARGV.each {|fasta|
  Bio::FlatFile.new(Bio::FastaFormat, File.new(fasta)).each {|seq|
    if (seq.definition =~/\{([A-Z|a-z|0-9|\ |\.]*)\}/)
      printf("%s\t%d\n", fasta, getTaxId($1))
    end
    break
  }
}
