#!/usr/bin/env ruby

require 'Newick'

if (ARGV.size != 1)
  STDERR.printf("usage: %s tree-file\n", $0)
  exit(1)
end

file = ARGV.pop

tree = NewickTree.fromFile(file)
dMatrix = tree.distanceMatrix

printf("    %d\n", dMatrix.keys.size)
dMatrix.keys.each {|key1|
  printf("%-16s ", key1)
  dMatrix.keys.each {|key2|
    printf("%f  ", dMatrix[key1][key2])
  }
  printf("\n")
}
