#!/usr/bin/env ruby

require 'Newick'

if (ARGV.size != 2)
  STDERR.printf("usage: %s tree-file reference-taxon\n", $0)
  exit(1)
end

treeFile, taxon = ARGV

tree = NewickTree.fromFile(treeFile)

relatives = tree.relatives(taxon)
p relatives