#!/usr/bin/env python

import argparse
import pickle
import base64
import re
import mistralai

def main():
    parser = argparse.ArgumentParser(description='oct2epub')
    parser.add_argument('-i', '--input', help='Input pkl ocr file')
    parser.add_argument('-o', '--output', help='Output markdown file')
    args = parser.parse_args()

    if args.input and args.output:
        with open(args.output, 'w') as o:
            with open(args.input, 'rb') as f:
                data = pickle.load(f)
                for page in data.pages:
                    pg = re.sub(r'^#','\n#', page.markdown)
                    pg = re.sub(r'-\n','', pg)
                    pg = re.sub(r'<br>',' ', pg)
                    pg = re.sub(r'<BR>',' ', pg)
                    print(pg, file=o)
                    if page.images:
                        for image in page.images:
                            img = image.image_base64.split(",")[1]
                            decoded_data = base64.b64decode(img)
                            with open(image.id, 'wb') as f2:
                                f2.write(decoded_data)
    else:
        print('Please provide -i or --input and -o or --output option.')

    
if __name__ == "__main__":
    main()
