#!/usr/bin/env ruby

require 'rubygems'
require 'bio'

if (ARGV.size != 1)
  STDERR.printf("usage: %s seq.fasta\n", $0)
  exit(1)
end

file = ARGV.shift

seen = Hash.new


Bio::FlatFile.new(Bio::FastaFormat, File.new(file)).each {|seq|
  contig = seq.entry_id.split("-").last
  if (seq.definition =~/\{([^\}]*)/)
    sp = $1
    #sp = sp.split(" ")[0]
    if (!seen[sp])
      print seq
      seen[sp] = true
    end
  end
}

