#!/usr/bin/env ruby

require 'ostruct'
require 'optparse'
opt = OpenStruct.new

ARGV.options {|opts|
  opts.banner << " rst [..rst...]"
  #opts.on(nil, "--report", "run apisReport when done") {|t| opt.report = t}    
  begin
    opts.parse!
  rescue
    STDERR.puts $!.message
    STDERR.puts opts
    exit(1)
  end
  if (ARGV.size < 1)
    STDERR.puts opts
    exit(1)
  end
}


ARGV.each {|rst|
  printed = false
  File.new(rst).each {|line|
    fields = line.split(" ")
    if (fields[2] =~ /\*/ && fields[3].to_f < 10)
      printf("%s\n", rst) if (!printed)
      print line
      printed = true
    end
  }
}
