#!/usr/bin/env ruby

$VERBOSE = nil

def required_gems(array)
  array.each do |item|
    begin
      require item
    rescue LoadError
      item = "newick-ruby" if item=="Newick"
      STDERR << "Gem #{item} missing. You need to gem install #{item}\n"
      exit(1)
    end
  end
end

def required_programs(array)
  array.each do |item|
      prog = `which #{item}`
      if prog == ""
        STDERR << "You don't have #{item} on your path, but it is required\n"
        exit(1)
      end
  end
end

required_gems ['rubygems', 'trollop', 'bio', 'Newick', 'fpdf']
required_programs ['paup']


origARGV = ARGV.dup # keep unparsed copy for grid

ARGV.push("--help") if ARGV.empty?
opts = Trollop::options do
  banner File.basename($0)
  opt :input, "fasta alignment(s)", :required =>true, :type =>:strings
  opt :bootstrap, "number of bootstraps (or 0 to not bootstrap)", :default=>100, :type=>:integer
  opt :estimate, "estimate branch lengths with puzzle"
  opt :algorithm, "algorithm from choices: nj, pars, ml", :default=>"nj", :type =>:string
  opt :outgroup, "use specified taxon as outgroup", :type=>:string
  opt :unrooted, "leave tree unrooted"
  opt :project, "run on grid with project number specified", :type=>:string
end

if (opts.algorithm != "pars" && opts.algorithm != "nj" && opts.algorithm != "ml")
  STDERR.printf("only pars, ml, and nj are supported\n")
  exit(1)
end

if opts.project
  cmd = $0
  keys = opts.keys - [:help, :input, :project]
  keys.each do |key|
    k = key.to_s
    val = opts[key]
    if val.is_a?(Array)
      val = val.join(" ")
    end
    cmd += " --#{key} #{val}" if !k.index("_given") && val
  end
  opts.input.each do |input|
    system("qsub -P #{opts.project} -cwd " + cmd + 
           " --input #{input}")
  end
  exit(0)
end

# is a fasta file DNA?
def isDNA?(fasta)
   seq = File.read(fasta, 10000).split("\n").grep(/^[^>]/).join
   seq.count("AGTCN").to_f / seq.length > 0.90
end

# provide aliased fasta name so programs like PHYLIP don't get confused by long names
def aliasFasta(fasta, ali, out, outgroup = nil)
   outFile = File.new(out, "w")
   aliFile = File.new(ali, "w") if (!ali.nil?)
   aliHash = Hash.new
   orfNum = "SID0000001"
   Bio::FlatFile.new(Bio::FastaFormat, File.new(fasta)).each do |seq|
      newName = orfNum
      name = seq.definition.split(" ").first
      newName = "SID0000000" if (outgroup == name)
      aliFile.printf("%s\t%s\n", newName, seq.definition) if (ali)
      aliHash[newName] = seq.definition.tr("(),:","_")
      seq.definition = newName
      outFile.print seq
      orfNum = orfNum.succ if (outgroup != name)
   end
   outFile.close
   aliFile.close if (ali)
   return aliHash
end

# given a NewickTree and an alignment add ML distances
def estimateMLBranchLengths(tree, alignFile, tmpdir)
  required_programs ['puzzle']
  outgroup = tree.taxa.sort.last
  tree.reroot(tree.findNode(outgroup))
  bClades = tree.clades(true)
  fasta2Phylip(alignFile, "#{tmpdir}/infile")
  tree.write("#{tmpdir}/intree")
  treepuzzle = "puzzle infile intree"
  system("cd #{tmpdir};echo  \"y\" | #{treepuzzle} > /dev/null")
  tree = NewickTree.fromFile("#{tmpdir}/intree.tree")
  tree.reroot(tree.findNode(outgroup))
  tree.addBootStrap(bClades)
  File.unlink(tmpdir+"/intree", tmpdir+"/intree.tree", tmpdir+"/infile")
  File.unlink(tmpdir+"/intree.dist", tmpdir+"/intree.puzzle")
  return tree
end

if Object.const_defined?("Bio") # has bioruby been loaded?
   # do this to avoid splitting on "|"
   class Bio::FastaFormat
      def full_id
         return definition.split(" ").first
      end
   end
end

# converts fasta to NEXUS format
def fasta2Nexus(alignFile, dna, nexFile = nil)
   seqs = Hash.new
   name = nil
   seqFile = File.new(alignFile)
   Bio::FlatFile.new(Bio::FastaFormat, seqFile).each do |seq|
      seqs[seq.full_id] = seq.seq.gsub("?","-").gsub(".","-")
   end
   seqFile.close
   if dna
      type = "NUC"
   else
      type = "PROT"
   end
   if (nexFile.nil?)
      out = STDOUT
   else
      out = File.new(nexFile, "w")
   end
   lineLen = 40
   aLen = seqs[seqs.keys.first].size
   out.print "#NEXUS\nBEGIN DATA;\n"
   out.print "DIMENSIONS NTAX=#{seqs.size} NCHAR=#{aLen};\n"
   out.print "FORMAT DATATYPE=#{type} INTERLEAVE MISSING=-;\n"
   out.print "MATRIX\n"
   pos = 0
   while (pos < aLen)
      seqs.keys.sort.each do |name|
         out.printf("%35s ", name)
         out.printf("%s\n", seqs[name][pos..pos + lineLen - 1])
      end
      pos += lineLen
      out.printf("\n")
   end
   out.print ";\nEND;\n"
   out.close if nexFile
end

# converts fasta to phylip format
def fasta2Phylip(alignFile, phyFile)
  seqs = Hash.new
  name = nil
  inFile = File.new(alignFile)
  inFile.each do |line|
    line.chomp!
    line.tr!("*","")
    if line =~ /^>/
      name = line[1..line.length].split(";").pop
      seqs[name] = ""
    else
      seqs[name] += line.gsub(".","-")
    end
  end
  inFile.close
  phy = File.new(phyFile, "w")
  lineLen = 60
  phy.printf("%d %d\n", seqs.size, seqs[name].length)
  pos = 0
  while (pos < seqs[name].length)
    seqs.keys.sort.each do |name|
      if pos == 0
        phy.printf("%-10s ", name)
      end
      phy.printf("%s\n", seqs[name][pos..pos + lineLen - 1])
    end
    pos += lineLen
    phy.printf("\n")
  end
  phy.close
end

# cleans up temporary files
def cleanup(dir)
  Dir.glob(dir+"/*").each do |file|
    File.unlink(file)
  end
  Dir.unlink(dir)
end

# main program loop
opts.input.each do |fasta|
  name = File.basename(fasta).split(".").first
  tmpdir = ENV["HOME"] + "/.tmp"
  Dir.mkdir(tmpdir) if !File.exists?(tmpdir)
  tmpdir += "/" + name + "_" + Time.now.to_f.to_s
  Dir.mkdir(tmpdir) if !File.exists?(tmpdir)
  tname = tmpdir + "/" + name
  dna = isDNA?(fasta)
  aliHash = aliasFasta(fasta, nil, tname, opts.trim)
  fasta2Nexus(tname, dna, tname + ".nex")
  out = File.new("#{tname}.nex", "a+")
  if (opts.outgroup)
    aliHash.keys.each do |key|
      out.print "Outgroup #{key};\n" if (aliHash[key] == opts.outgroup)
    end
  end
  if (opts.algorithm == "pars")
    out.print "Set Criterion=parsimony;\n"
    if (opts.bootstrap == 0)
      out.print "hsearch;\n"
    else
      out.print "boot nreps=#{opts.bootstrap} keepall=y;\n"
    end
  elsif (opts.algorithm == "ml")
    out.print "Set Criterion=likelihood;\n"
    if (opts.bootstrap == 0)
      out.print "hsearch;\n"
    else
      out.print "boot nreps=#{opts.bootstrap} keepall=y;\n"
    end
  elsif (opts.algorithm == "nj")
    out.print "Set Criterion=distance;\n"
    if (opts.bootstrap == 0)
      out.print "nj;\n"
    else
      out.print "boot nreps=#{opts.bootstrap} search=nj keepall=y;\n"
    end
  else
    out.print("hsearch;\n")
  end
  
  out.print "savetrees from=1 to=1 format=phylip file=#{tmpdir}/out.tree;\n"
  out.print "quit;\n"
  out.close
  system("paup #{tname}.nex")
  tree = NewickTree.fromFile("#{tmpdir}/out.tree")
  tree.fixPhylip
  tree = estimateMLBranchLengths(tree, tname, tmpdir) if (opts.estimate)
  tree.unAlias(aliHash)
  if (opts.outgroup)
    outNode = tree.findNode(opts.outgroup)
    if (outNode.nil?)
      STDERR.printf("taxon #{opts.outgroup} not found in tree!\n")
    else
      tree = tree.reroot(outNode)
    end 
  elsif (!opts.unrooted)
    tree = tree.midpointRoot
  end  
  tree.write("#{name}_#{opts.algorithm}.tree")
  tree.draw("#{name}_#{opts.algorithm}.tree.pdf")
  cleanup(tmpdir)
end
