#!/usr/bin/env ruby

require 'rubygems'
require 'optimist'

ARGV.push("-h") if ARGV.empty?

opts = Optimist::options do
  banner File.basename($0)
  opt :blast, "blast program", :default=>"blastp", :type => :string
  opt :evalue, "BLAST evalue", :default => 1e-9, :type => :float
  opt :input, "FASTA input file(s) to blast", :required => true, :type => :strings
  opt :maxhits, "max number of BLAST hits", :default => 50, :type => :integer
end


opts.input.each do |pep1|
  opts.input.each do |pep2|
    if (pep1 != pep2)
        if (Dir.glob("#{pep2}_vs_#{pep1}*").empty?)
          system("blastp -evalue #{opts.evalue} -max_target_seqs #{opts.maxhits} -db #{pep1} -query #{pep2} -outfmt 6 -out #{pep1}_vs_#{pep2}.blast")
        else
          STDERR.printf("Skipping #{pep1}_vs_#{pep2} due to existing results...\n")
      end
    end
  end
end
