#!/usr/bin/env ruby 

require 'trollop'

def required_programs(array)
  array.each do |item|
      prog = `which #{item}`
      if prog == ""
        STDERR << "You don't have #{item} on your path, but it is required\n"
        exit(1)
      end
  end
end

required_programs ["pdf2htmlEX"]

ARGV.push("--help") if ARGV.empty?
opts = Trollop::options do
  banner File.basename($0)
  opt :input, "pdf file(s)", :required=>true, :type=>:strings
end

opts.input.each do |pdf|
  name = File.basename(pdf,".pdf").tr(" ():/\\","_")
  cmd =  "pdf2htmlEX --embed-css 0 --embed-font 0 --embed-image 0 "
  cmd += "--embed-javascript 0 --embed-outline 0 --split-pages 1 "
  cmd += "--bg-format jpg --hdpi 150 --vdpi 150 --fit-width 1275 "
  cmd += "--fit-height 1650 --css-filename #{name}.css "
  cmd += "--correct-text-visibility 1 --no-drm 1 #{pdf}"
  system(cmd) if !File.exists?(name+".css")
  File.unlink("fancy.min.css") if File.exists?("fancy.min.css")
  File.unlink("pdf2htmlEX.min.js") if File.exists?("pdf2htmlEX.min.js")
  File.unlink("compatibility.min.js") if File.exists?("compatibility.min.js")
  Dir.glob("*.page").each do |page|
    out = File.new(page.sub(".page",".xhtml"), "w")
    out.printf("<?xml version='1.0' encoding='UTF-8'?>\n")
    out.printf("<html xmlns:epub=\"http://www.idpf.org/2007/ops\"\n")
    out.printf("xmlns=\"http://www.w3.org/1999/xhtml\">\n")
    out.printf("<head><meta charset=\"utf-8\"/>\n")
    out.printf("<meta name=\"generator\" content=\"pdf2htmlEX\"/>\n")
    out.printf("<link rel=\"stylesheet\" type=\"text/css\"\n")
    out.printf("href=\"base.min.css\"/><link rel=\"stylesheet\"\n")
    out.printf("type=\"text/css\" href=\"#{name}.css\"/>\n")
    out.printf("<meta name=\"viewport\" ")
    out.printf("content=\"width=1275, height=1650\"/>\n")
    out.printf("<title></title></head><body><div id=\"page-container\">\n")
    File.new(page).each do |line|
      out.print(line)
    end
    out.printf("</div>\n")
    out.printf("</body>\n")
    out.printf("</html>\n")
    out.close
    File.unlink(page)
  end
  if !File.exists?("mimetype")
    out = File.new("mimetype","w")
    out.printf("application/epub+zip")
    out.close
  end
  Dir.mkdir("META-INF") if !Dir.exists?("META-INF")
  Dir.mkdir("OEBPS") if !Dir.exists?("OEBPS")
  if !File.exists?("META-INF/container.xml")
    out = File.new("META-INF/container.xml", "w")
    out.printf("<?xml version='1.0' encoding='UTF-8'?>\n")
    out.printf("<display_options>\n<platform name=\"*\">\n")
    out.printf("<option name=\"fixed-layout\">true</option>\n")
    out.printf("<option name=\"specified-fonts\">true</option>\n")
    out.printf("</platform>\n</display_options>\n")
    out.close
  end
end
