#!/usr/bin/env ruby

$VERBOSE = nil

def required_gems(array)
  array.each do |item|
    begin
      require item
    rescue LoadError
      item = "newick-ruby" if item=="Newick"
      STDERR << "Gem #{item} missing. You need to gem install #{item}\n"
      exit(1)
    end
  end
end

def required_programs(array)
  array.each do |item|
      prog = `which #{item}`
      if prog == ""
        STDERR << "You don't have #{item} on your path, but it is required\n"
        exit(1)
      end
  end
end

required_gems ['rubygems', 'trollop', 'bio', 'Newick', 'fpdf']
required_programs ['dnapars', 'protpars', 'dnadist', 'protdist']

origARGV = ARGV.dup # keep unparsed copy for grid

ARGV.push("--help") if ARGV.empty?
opts = Trollop::options do
  banner File.basename($0)
  opt :input, "fasta alignment(s)", :required =>true, :type =>:strings
  opt :bootstrap, "number of bootstraps (or 0 to not bootstrap)", :default=>100, :type=>:integer
  opt :estimate, "estimate branch lengths with puzzle"
  opt :algorithm, "algorithm from choices: nj, pars, ml", :default=>"nj", :type =>:string
  opt :outgroup, "use specified taxon as outgroup", :type=>:string
  opt :unrooted, "leave tree unrooted"
  opt :project, "run on grid with project number specified", :type=>:string
  opt :pam, "use PAM model"
  opt :gamma, "use gamma distrib. rates"
end

if (opts.algorithm != "pars" && opts.algorithm != "nj" && opts.algorithm != "ml")
  STDERR.printf("only pars, ml, and nj are supported\n")
  exit(1)
end

if opts.project
  cmd = $0
  keys = opts.keys - [:help, :input, :project]
  keys.each do |key|
    k = key.to_s
    val = opts[key]
    if val.is_a?(Array)
      val = val.join(" ")
    end
    cmd += " --#{key} #{val}" if !k.index("_given") && val
  end
  opts.input.each do |input|
    system("qsub -P #{opts.project} -cwd " + cmd + 
           " --input #{input}")
  end
  exit(0)
end

# is a fasta file DNA?
def isDNA?(fasta)
   seq = File.read(fasta, 10000).split("\n").grep(/^[^>]/).join
   seq.count("AGTCN").to_f / seq.length > 0.90
end

# provide aliased fasta name so programs like PHYLIP don't get confused by long names
def aliasFasta(fasta, ali, out, outgroup = nil)
   outFile = File.new(out, "w")
   aliFile = File.new(ali, "w") if (!ali.nil?)
   aliHash = Hash.new
   orfNum = "SID0000001"
   Bio::FlatFile.new(Bio::FastaFormat, File.new(fasta)).each do |seq|
      newName = orfNum
      name = seq.definition.split(" ").first
      newName = "SID0000000" if (outgroup == name)
      aliFile.printf("%s\t%s\n", newName, seq.definition) if (ali)
      aliHash[newName] = seq.definition.tr("(),:","_")
      seq.definition = newName
      outFile.print seq
      orfNum = orfNum.succ if (outgroup != name)
   end
   outFile.close
   aliFile.close if (ali)
   return aliHash
end

# given a NewickTree and an alignment add ML distances
def estimateMLBranchLengths(tree, alignFile, tmpdir)
  required_programs ['puzzle']
  outgroup = tree.taxa.sort.last
  tree.reroot(tree.findNode(outgroup))
  bClades = tree.clades(true)
  fasta2Phylip(alignFile, "#{tmpdir}/infile")
  tree.write("#{tmpdir}/intree")
  treepuzzle = "puzzle infile intree"
  system("cd #{tmpdir};echo  \"y\" | #{treepuzzle} > /dev/null")
  tree = NewickTree.fromFile("#{tmpdir}/intree.tree")
  tree.reroot(tree.findNode(outgroup))
  tree.addBootStrap(bClades)
  File.unlink(tmpdir+"/intree", tmpdir+"/intree.tree", tmpdir+"/infile")
  File.unlink(tmpdir+"/intree.dist", tmpdir+"/intree.puzzle")
  return tree
end

# converts fasta to phylip format
def fasta2Phylip(alignFile, phyFile)
  seqs = Hash.new
  name = nil
  inFile = File.new(alignFile)
  inFile.each do |line|
    line.chomp!
    line.tr!("*","")
    if line =~ /^>/
      name = line[1..line.length].split(";").pop
      seqs[name] = ""
    else
      seqs[name] += line.gsub(".","-")
    end
  end
  inFile.close
  phy = File.new(phyFile, "w")
  lineLen = 60
  phy.printf("%d %d\n", seqs.size, seqs[name].length)
  pos = 0
  while (pos < seqs[name].length)
    seqs.keys.sort.each do |name|
      if pos == 0
        phy.printf("%-10s ", name)
      end
      phy.printf("%s\n", seqs[name][pos..pos + lineLen - 1])
    end
    pos += lineLen
    phy.printf("\n")
  end
  phy.close
end

# cleans up temporary files
def cleanup(dir)
  Dir.glob(dir+"/*").each do |file|
    File.unlink(file)
  end
  Dir.unlink(dir)
end

# main program loop
opts.input.each do |fasta|
  name = File.basename(fasta).split(".").first
  tmpdir = ENV["HOME"] + "/.tmp"
  Dir.mkdir(tmpdir) if !File.exists?(tmpdir)
  tmpdir += "/" + name + "_" + Time.now.to_f.to_s
  Dir.mkdir(tmpdir) if !File.exists?(tmpdir)
  tname = tmpdir + "/" + name
  dna = isDNA?(fasta)
  aliHash = aliasFasta(fasta, nil, tname, opts.outgroup)
  fasta2Phylip(tname, "#{tname}.phy")
  File.unlink("#{tmpdir}/infile") if (File.exists?("#{tmpdir}/infile"))
  File.unlink("#{tmpdir}/outfile") if (File.exists?("#{tmpdir}/outfile"))
  File.unlink("#{tmpdir}/outtree") if (File.exists?("#{tmpdir}/outtree"))
  File.rename("#{tname}.phy", "#{tmpdir}/infile")
  
  if (opts.bootstrap > 0)
    odd = (2 * rand(40)) + 1
    system("cd #{tmpdir};echo -e 'R\n#{opts.bootstrap}\nY\n#{odd}\n' | seqboot")
    File.rename("#{tmpdir}/outfile", "#{tmpdir}/infile")
  end
  if (opts.algorithm == "pars")
    if (dna)
      pars = "dnapars"
    else
      pars = "protpars"
    end
    if (opts.bootstrap == 0)
      system("cd #{tmpdir}; echo -e 'Y\n' | #{pars}") 
    else
      odd = (2 * rand(40)) + 1
      system("cd #{tmpdir}; echo -e 'M\n\D\n#{opts.bootstrap}\n#{odd}\n2\nY\n' | #{pars}") 
    end
  elsif (opts.algorithm == "nj")
    if (dna)
      dist = "dnadist"
    else
      dist = "protdist"
    end
    if (opts.bootstrap == 0)
      system("cd #{tmpdir}; echo -e 'Y\n' | #{dist}")
      neighbor = "echo -e 'Y\n' | neighbor"
    else
      system("cd #{tmpdir}; echo -e 'M\nD\n#{opts.bootstrap}\nY\n' | #{dist}")
      odd = (2 * rand(40)) + 1
      neighbor = "echo -e 'M\n#{opts.bootstrap}\n#{odd}\nY\n' | neighbor"
    end
    File.rename("#{tmpdir}/outfile", "#{tmpdir}/infile")
    system("cd #{tmpdir}; #{neighbor}")
  elsif (opts.algorithm == "ml")
    pam = ""
    after = "Y\n"
    if (dna)
      ml = "dnaml"
    else
      ml = "proml"
      pam = "P\nP\n" if (opts.pam)
      pam += "R\n" if (opts.gamma)
    end
    aft = "Y\n"
    aft += "1.41\n9\n" if (opts.gamma)
    if (opts.bootstrap == 0)
      system("cd #{tmpdir}; echo -e '#{pam}#{aft}' | #{ml}") 
    else
      odd = (2 * rand(40)) + 1
      system("cd #{tmpdir};echo -e 'M\n\D\n#{opts.bootstrap}\n#{odd}\n2\n#{pam}#{aft}'|#{ml}") 
    end
  end
 
  if (!opts.noboot)
    File.rename("#{tmpdir}/outtree", "#{tmpdir}/intree")
    File.unlink("#{tmpdir}/outfile")
    system("cd #{tmpdir}; echo -e 'Y\n' | consense")
  end
  File.rename("#{tmpdir}/outtree", "#{tname}.tree")
  tree = NewickTree.fromFile("#{tname}.tree")
  tree.fixPhylip
  tree = estimateMLBranchLengths(tree, tname, tmpdir) if (opts.estimate)
  tree.unAlias(aliHash)
  if (opts.outgroup)
    outNode = tree.findNode(opts.outgroup)
    if (outNode.nil?)
      STDERR.printf("taxon #{opts.outgroup} not found in tree!\n")
    elsif (!opts.unrooted)
      tree = tree.reroot(outNode)
    end
  else
    tree = tree.midpointRoot
  end
  if (!opts.gamma)
    tree.write("#{name}_#{opts.algorithm}.tree")
    tree.draw("#{name}_#{opts.algorithm}.tree.pdf")
  else
    tree.write("#{name}_#{opts.algorithm}_gamma.tree")
    tree.draw("#{name}_#{opts.algorithm}_gamma.tree.pdf")
  end
  cleanup(tmpdir)
end
