#!/usr/bin/env ruby

if (ARGV.size != 2)
  STDERR.printf("usage: %s csv num-to-pick\n", $0)
  exit(1)
end

csv, num = ARGV

num = num.to_i
total = 0

total = `wc -l #{csv}`.to_i

STDERR.printf("%d lines in file\n", total)

pick = Hash.new
num.times {|i|
  rnum = rand(total)
  if (pick[rnum].nil?)
    pick[rnum] = true
  else
    done = false	
    while (!done)
      rnum = rand(total)
      if (pick[rnum].nil?)
        pick[rnum] = true
        done = true
      end
    end
  end
}

total = 0
File.new(csv).each {|line|
  print line if (pick[total])
  total += 1
}
