#!/usr/bin/env ruby

require 'ostruct'
require 'optparse'
opt = OpenStruct.new

ARGV.options {|opts|
  opts.banner << " csv"
  #opts.on(nil, "--report", "run apisReport when done") {|t| opt.report = t}    
  begin
    opts.parse!
  rescue
    STDERR.puts $!.message
    STDERR.puts opts
    exit(1)
  end
  if (ARGV.size != 1)
    STDERR.puts opts
    exit(1)
  end
}

csv, rest = ARGV

categories = nil
seen = Hash.new
File.new(csv).each {|line|
  fields = line.gsub("\"","").chomp.split(",")
  if (categories.nil?)
    categories = fields
    print line
    next
  end
  sp = fields[1].split(" ").first
  if (!seen[sp])
    seen[sp] = true
    print line
  end
}
