#!/usr/bin/env ruby

require 'rubygems'
require 'optimist'

ARGV.push("--help") if ARGV.empty?

opts = Optimist::options do
  banner File.basename($0) 
  opt :csv, "csv file to pick from", :required =>true, :type => :string
  opt :num, "number of lines to pick", :required=>true, :type=> :integer
  opt :header, "include header line"
end

total = `wc -l #{opts.csv}`.to_i

STDERR.printf("%d lines in file\n", total)

pick = Hash.new
opts.num.times do |i|
  rnum = rand(total)
  rnum += 1 if opts.header
  if (pick[rnum].nil?)
    pick[rnum] = true
  else
    done = false	
    while (!done)
      rnum = rand(total)
      if (pick[rnum].nil?)
        pick[rnum] = true
        done = true
      end
    end
  end
end

total = 0
File.new(opts.csv).each do |line|
  print line if opts.header && total == 0
  print line if (pick[total])
  total += 1
end
