#!/usr/bin/env ruby

require 'optparse'

@grid = false

ARGV.options {|opts|
  opts.banner << " fasta [fasta...fasta...]"
  begin
    opts.parse!
  rescue
    STDERR.puts $!.message
    STDERR.puts opts
    exit(1)
  end
  if (ARGV.size < 1)
    STDERR.puts opts
    exit(1)
  end
}

ARGV.each {|pep1|
  ARGV.each {|pep2|
    b1 = "#{pep1}_vs_#{pep2}.btab"
    b2 = "#{pep2}_vs_#{pep1}.btab"
    if (pep1 != pep2)
      system("bestRecipBtab #{b1} #{b2} > #{pep2}_vs_#{pep1}.recip")
      system("bestRecipBtab #{b2} #{b1} > #{pep1}_vs_#{pep2}.recip")
    end
  }
}

