#!/usr/bin/env ruby

require 'ostruct'
require 'optparse'
require 'bio'
require 'SunGrid'

opt = OpenStruct.new
opt.command = "tmhmm"
opt.project = nil
opt.queue = "default"
opt.gridSize = nil
$VERBOSE = nil


ARGV.options do |opts|
  opts.banner << " fasta [fasta...]"
  opts.on("-c ", "--command ", String,
         "command to run hmm search (#{opt.command})") {|t| opt.command = t}
  opts.on("-p", "--project ", String,  
          "JCVI project number") {|t| opt.project = t}
  opts.on("-q ", "--queue ", String, 
	  "grid queue to use (default #{opt.queue})") {|t| opt.queue = t}
  opts.on("-z ", "--size ", Integer,  
	  "number of sequences per each grid job (default automatic)") {|t| opt.gridSize = t} 
  begin
    opts.parse!
  rescue
    STDERR.puts $!.message
    STDERR.puts opts
    exit(1)
  end
  if (ARGV.size < 1)
    STDERR.puts opts
    exit(1)
  end
end

if (opt.project.nil?)
  STDERR.printf("A project is required\n")
  exit(1)
end


ARGV.each do |file|
  opt.gridSize = 10000 if (opt.gridSize.nil?)
  outName = File.basename(file, ".pep") + "_tmhmm.txt"
  next if File.exist?(outName) 
  if (!File.exists?(file))
    STDERR.printf("File %s does not exist!\n", file)
    next
  end
  hmm = "#{opt.command} tmhmm_input.$SGE_TASK_ID.out "
  grid = SunGrid.new(hmm, opt.project, "4G")
  count = 0
  out = nil
  Bio::FlatFile.new(Bio::FastaFormat, File.new(file)).each do |seq|
    if (count % opt.gridSize == 0)
      out.close if (!out.nil?)
      out = File.new(grid.next, "w")
    end 
    out.print seq
    count += 1
  end
  out.close
  grid.submit(sync = true)
  grid.cleanup
  outFile = File.new(outName, "w")
  out = "";
  File.new("tmhmm.out").each do |line|
    line.chomp!
    if (line !~ /\/usr\/local\/bin/ )
      if (line =~ /\#/ )
        if (line =~ /^\# ([^\s]+) Length: (\d+)\s*/ ) 
          if (out != "") 
            outFile.print out + "\n"
            out = ""
          end
          a = $1;
          outFile.printf("%s len=%s ", a, $2)
        elsif (line =~ /^\# ([^\s]+) Number of predicted TMHs:\s+(\d+)\s*/ )
          a = $1;
          outFile.printf("PredHel = %s ", $2)
        end
      else 
        out += "Topology=" if (out !~ /Topology/) 
        (a, b, property, topology) = line.split("\t")
        if (property == "inside") 
          out += "i"
        elsif (property ==  "outside") 
          out += "o"
        else 
          topology =~ /\s+(\d+)\s+(\d+)/
          out += $1 + "-" + $2
        end
      end
    end
  end
  outFile.close
  File.unlink("tmhmm.out")
end
