#!/usr/bin/env ruby 

require 'trollop'
require 'mysql'
require 'sqlite3'

ARGV.push("--help") if ARGV.empty?
opts = Trollop::options do
  banner File.basename($0)
  opt :host, "db host (for mysql)", :default=>"mysql-lan-pro", :type=>:string
  opt :user, "user (for mysql)", :default=>"jbadger", :type=>:string
  opt :password, "password (for mysql)", :default=>"plankton", :type=>:string
  opt :db, "database (or file for sqlite3)", :required=>:true, :type=>:string
  opt :file, "query is file"
  opt :sql, "SQL query", :required=>:true, :type=>:string
  opt :verbose, "verbose reporting"
end

if File.exists?(opts.db)
  db = SQLite3::Database.new(opts.db)
else
  db = Mysql::new(opts.host, opts.user, opts.password, opts.db)
end

if opts.file
  sql = File.read(opts.sql).split(";")
else
  sql = opts.sql.split(";")
end

sql.each do |s|
  STDERR.printf("%s\n", s) if opts.verbose
  results = db.query(s)
  if results
    results.each do |row|
      print row.to_a.join("\t") + "\n"
    end
  end
end
db.close
