#!/usr/bin/env ruby


if (ARGV.size != 2)
  STDERR.printf("Usage: %s taxonomy.txt num\n", File.basename($0))
  exit(1)
end

taxonomy, num = ARGV

ranks = Hash.new
taxa = Hash.new
parents = Hash.new
seen = Hash.new

STDERR << "Loading taxonomy....\n"
File.new(taxonomy).each do |line|
  id, name, parent, rank = line.chomp.split("\t")
  id = id.to_i
  parent = parent.to_i
  taxa[id] = name
  parents[id] = parent
  ranks[id] = rank
end


id = num.to_i

arank=["kingdom","phylum","class","order","family","genus","species"]

if (taxa[id])
  num = 0
  while (id != 1)
    printf("%d\t%s\tncbi=%s\tapis=%s (rank %d)\n", id, 
    taxa[id],ranks[id], arank[6-num], 7 - num)
    id = parents[id]
    num += 1
  end
end
