#!/usr/bin/env ruby 

require 'rubygems'
require 'bio'    
require 'trollop'
require 'ZFile'

ARGV.push("--help") if ARGV.empty?
opts = Trollop::options do
  banner File.basename($0)
  opt :input, "Input fasta file", :required=>true, :type=>:string
  opt :header, "keep sequence header", :default=>false
  opt :noambig, "remove N's, X's", :default=>false
  opt :remove, "remove alignment", :default=>false
  opt :linelen, "line Length", :default=>60, :type=>:integer
  opt :fastq, "read in fastq"
end

if opts.fastq
  form = Bio::Fastq
else
  form = Bio::FastaFormat
end

Bio::FlatFile.new(form, ZFile.new(opts.input)).each do |seq|
  seq.seq.gsub!(/-|\./,"") if opts.remove
  seq.seq.gsub!(/N|n|X|x/,"") if opts.noambig
  if !opts.header || opts.fastq
    header = seq.entry_id 
  else
    header = seq.definition
  end
  print seq.seq.upcase.to_fasta(header, opts.linelen)
end
