#!/usr/bin/env ruby 

require 'rubygems'
require 'bio'    
require 'trollop'
require 'ZFile'

ARGV.push("--help") if ARGV.empty?
opts = Trollop::options do
  banner File.basename($0)
  opt :input, "Input fasta file", :required=>true, :type=>:string
  opt :header, "keep sequence header", :default=>false
  opt :noambig, "remove N's, X's", :default=>false
  opt :remove, "remove alignment", :default=>false
end

Bio::FlatFile.new(Bio::FastaFormat, ZFile.new(opts.input)).each do |seq|
  seq.seq.gsub!(/-|\./,"") if opts.remove
  seq.seq.gsub!(/N|n|X|x/,"") if opts.noambig
  seq.definition = seq.entry_id if !opts.header
  print seq.seq.upcase.to_fasta(seq.definition, 60)
end
