#!/usr/bin/env ruby

require 'rubygems'
require'bio'
include Bio    

if (ARGV.size != 1)
  STDERR.printf("usage: %s seq.fasta\n", $0)
  exit(1)
end

file = ARGV.shift


FlatFile.new(FastaFormat, File.new(file)).each {|seq|
  trimSeq = seq.seq
  2.step(seq.length, 3) {|i|
    trimSeq[i] = "-" 
  }
  print Sequence.new(trimSeq.upcase).to_fasta(seq.definition, 60)
}
