#!/usr/bin/env ruby

if (ARGV.size != 1)
  STDERR.printf("Usage: %s blast-file\n", File.basename($0))
  exit(1)
end


blastFile = ARGV.first

lines = ""
File.new(blastFile).each do |line|
  if (line =~/^BLAST/ || line =~/^TBLAST/)
    if (lines != "")
      if lines !~ /\*\*\* No hits found/
	      print lines
      end
      lines = ""
    end
  end
  lines += line
end

if lines !~ /\*\*\* NONE/
  print lines
end
