#!/usr/bin/env ruby

require 'trollop'
require 'ZFile'
require 'bio'

ARGV.push("--help") if ARGV.empty?
opts = Trollop::options do
  banner File.basename($0)
  opt :input, "input file", :required=>true, :type=>:string
  opt :above, "level to include above", :default=>0
end

def computeLKT(tax, above = 0)
  tax = tax.split(";")
  good_tax = tax.select{|x| x !~ /uncultured|unidentified|metagenome/}
  lkt = good_tax.last
  upper = good_tax[good_tax.index(lkt)-above]
  if lkt =~/^bacterium/
    lkt = good_tax[good_tax.index(lkt)-1]+"_"+lkt
    lkt = lkt.sub("bacterium ","")
  end
  if above > 0
    lkt = upper+"_"+lkt if lkt !~/#{upper}/
  end
  lkt.gsub(" ","_")
end

Bio::FlatFile.new(Bio::FastaFormat, ZFile.new(opts.input)).each do |seq|
  lkt = computeLKT(seq.definition.split(" ",2).last, opts.above)
  name = seq.entry_id + "_" + lkt
  print Bio::Sequence.new(seq.seq).to_fasta(name, 60)
end
