#!/usr/bin/env ruby

require 'rubygems'
require'bio'
include Bio    

if (ARGV.size != 1)
  STDERR.printf("usage: %s seq.fasta\n", $0)
  exit(1)
end

file = ARGV.shift

seqs = Hash.new

FlatFile.new(FastaFormat, File.new(file)).each {|seq|
  seqs[seq.definition] = seq
}

seqs.keys.sort.each {|name|
  print seqs[name]
}
