#!/usr/bin/env ruby 

require 'optimist'

ARGV.push("--help") if ARGV.empty?
opts = Optimist::options do
  banner File.basename($0)
  opt :input, "input fastq file(s)", :required=>true, :type=>:strings
  opt :paired, "fastq are paired"
  opt :reference, "bowtie reference", :required=>true, :type=>:string
  opt :execute, "execute command rather than printing it" 	
end

bowtie = File.expand_path(`which bowtie2`.chomp)

if opts.execute
  run = method(:system)
else
  def println(string)
    print(string+"\n")
  end
  run = method(:println)
end

printf("#!/bin/bash\n") if !opts.execute

run.call("cd #{ENV["PWD"]}")

reference = File.expand_path(opts.reference)

while !opts.input.empty?
  fq = opts.input.shift
  if opts.paired
    fq2 = opts.input.shift
    cmd = bowtie + " -x #{reference} -1 #{fq} -2 #{fq2} > #{fq}.bam"
  else
    cmd = bowtie + " -x #{reference} -U #{fq} > #{fq}.bam"
  end
  if !File.exists?(fq+".bam")
    run.call(cmd)
  end
end
