#!/usr/bin/env ruby 

require 'optimist'
require 'bio'    
require 'ZFile'

ARGV.push("--help") if ARGV.empty?
opts = Optimist::options do
  banner File.basename($0)
  opt :input, "input file", :required=>true, :type=>:string
  opt :len, "shred length", :default=>1000
  opt :max_len, "maximum length", :default=>1950
  opt :min_len, "minimum length", :default=>500
  opt :overlap, "overlap length", :default=>500
  opt :fastq, "output fastq format", :default=>false
end

Bio::FlatFile.new(Bio::FastaFormat, ZFile.new(opts.input)).each do |seq|
  (0..seq.length).step(opts.overlap) do |i|
    s = seq.seq[i,opts.len]
    header = seq.entry_id + "_" + (i + 1).to_s + "_" +
             (i + opts.len).to_s
    if s.length >= opts.min_len
      if opts.fastq
        print "@"+header+"\n"+s+"\n+\n"+"A"*s.length+"\n"
      else
        print s.to_fasta(header, 60)
      end
    end
  end
end
