#!/usr/bin/env ruby

if (ARGV.size != 2)
  STDERR.printf("usage: %s file pattern\n", $0)
  exit(1)
end

file, pat = ARGV

out = nil
num = 1

File.new(file).each do |line|
  if (line =~/#{pat}/)
    out.close if (!out.nil?)
    out = File.new(file + "." + num.to_s, "w")
    num += 1
  end
  out.print line
end
out.close
