#!/usr/bin/env ruby

require 'rubygems'
require'bio'
include Bio

if (ARGV.size != 1)
  STDERR << "usage: fasta-file\n" 
  exit(1)
end

fasta, rest = ARGV

oldAcc = "fred"
out = nil
FlatFile.new(FastaFormat,File.new(fasta)).each {|seq|
  if (seq.entry_id != oldAcc && !seq.entry_id.nil?)
    out.close if (!out.nil?)
    fileName = seq.entry_id.tr(" /;'","_") + ".pep".tr("/;'","")
    if (File.exists?(fileName))
      STDERR.printf("%s already exists. Appending\n", fileName)
    end
    out = File.new(fileName, "a+")
  end
  out.print seq
  if (seq.entry_id.nil?)
    STDERR.printf("unlabled sequence: %s\n", seq.definition)
  end
  oldAcc = seq.entry_id if (seq.entry_id != nil)
}
out.close
