#!/usr/bin/env ruby

require 'optparse'
require 'ostruct'
require 'rubygems'
require 'bio'

opt = OpenStruct.new
o = OptionParser.new
o.banner << " blast-file"
#o.on("-v", "--verbose", "Run verbosely") {opt.verbose = true}
begin
  o.parse!
rescue
  STDERR << $!.message << "\n"
  STDERR << o
  exit(1)
end
if (ARGV.size != 1)
  STDERR << o
  exit(1)
end

blast, rest = ARGV

Bio::Blast::Default::Report.open(blast, "r").each do |query|
  qname =  query.query_def.split(" ").first
  p qname
  query.each do |hit|
  end
end
