#!/usr/bin/env ruby

require 'csv'

if (ARGV.size != 1)
  STDERR << "Usage: " << File.basename($0) << " csv-file\n"
  exit(1)
end

csv = ARGV.first

assignment = Hash.new
CSV.foreach(csv, :headers => true) do |row|
  name, tax = row["Seq Name"], row["Relaxed Classification"]
  if (name =~/(NODE_|contig|ctg[0-9]*)_/)  
    contig = $1
    assignment[contig] = [] if assignment[contig].nil?
    tax = tax.split("; ")
    0.upto(6) do |i|
      assignment[contig][i] = Hash.new if !assignment[contig][i]
      tax[i] = "Mixed" if !tax[i]
      assignment[contig][i][tax[i]] = 0 if !assignment[contig][i][tax[i]]
      assignment[contig][i][tax[i]] += 1
    end
  end
end
print ["Contig", "Orfs", "Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species"].to_csv

rows = Hash.new
orfs = Hash.new
assignment.keys.sort.each do |contig|
  row = [contig]
  0.upto(6) do |i|
    tot = assignment[contig][i].values.reduce(:+)
    row.push(tot) if (row.size == 1)
    tx = ""
    assignment[contig][i].keys.sort {|x, y| assignment[contig][i][y] <=> assignment[contig][i][x]}.each do |taxon|
      next if taxon == "Mixed"
      percent = ((assignment[contig][i][taxon]*100)/tot)
      tx += taxon + " " + percent.to_s + "% " if percent > 5
    end
    row.push(tx)
  end
  rows[contig] = row
  orfs[contig] = row[1]
  print row.to_csv
end

rows.keys.sort {|x, y| orfs[y] <=> orfs[x]}.each do |key|
  print rows[key].to_csv
end
