#!/usr/bin/env python

import argparse
from Bio import SeqIO, SeqUtils

parser = argparse.ArgumentParser()
parser.add_argument("-i", "--input", nargs="*", required=True,
                    help="input FASTA/Fastq file(s)")
parser.add_argument("-t", "--total", action="store_true", 
                    help="return totaled results")
parser.add_argument("-q", "--fastq", action="store_true", 
                    help="input is in fastq format")
args = parser.parse_args()

if args.fastq:
    format = "fastq"
else:
    format = "fasta"

gcs = 0
lens = 0
ambigs = 0
count = 0

for inp in args.input:
    handle = open(inp, "rU")
    for seq in SeqIO.parse(handle, format):
        slen = len(seq)
        gc = SeqUtils.GC(seq.seq)
        ambig = seq.seq.count("N")
        if args.total:
            lens += slen
            gcs += gc
            count += 1
        else:
            print("%10s %6d %3.1f" % (seq.id, slen, gc))
    handle.close()

if args.total:
    print("%10s %6d %3.1f" % ("Total", lens/count, gcs/count))
