#!/usr/bin/env ruby

require 'optparse'

ARGV.options {|opts|
  opts.banner << " tab.txt"
  begin
    opts.parse!
  rescue
    STDERR.puts $!.message
    STDERR.puts opts
    exit(1)
  end
  if (ARGV.size != 1)
    STDERR.puts opts
    exit(1)
  end
}

tab, rest = ARGV

File.new(tab).each {|line|
  fields = line.chomp.split("\t")
  fields.each {|field|
    if field.index(",")
      printf("\"%s\",", field)
    else
      printf("%s,", field)
    end
  }
  printf("\n")
}
