#!/usr/bin/env ruby

require 'ostruct'
require 'apis'
require 'Hmm'
require 'Newick'
require 'optparse'
opt = OpenStruct.new

ARGV.options {|opts|
  opts.banner << " pep-file att-file"
  #opts.on(nil, "--report", "run apisReport when done") {|t| opt.report = t}    
  begin
    opts.parse!
  rescue
    STDERR.puts $!.message
    STDERR.puts opts
    exit(1)
  end
  if (ARGV.size != 2)
    STDERR.puts opts
    exit(1)
  end
}

pep, att = ARGV

tax = loadTax(att)

seen = Hash.new
FastaDB.new(pep).each {|seq|
  contig, rest = seq.name.split("__")
  contig = contig.split("-").last if (contig.index("-"))
  if (!tax[contig] && !seen[contig])
    STDERR.printf("%s missing from %s\n", contig, att)
  end
  seen[contig] = true
}
