#!/usr/bin/env ruby

if (ARGV.size != 1)
  STDERR.printf("usage: %s trees\n", $0)
  exit(1)
end


data = File.new(ARGV.first).read

data.gsub!(/\)[0-9]+/, ")")
data.gsub!(/\:[0-9]+[0-9|\.|-|e|E]*/, "")
print data
