#!/usr/bin/env ruby

require 'optparse'
require 'ostruct'

opt = OpenStruct.new
o = OptionParser.new
o.banner << " tpz-file [tpz...]"
begin
  o.parse!
rescue
  STDERR << $!.message << "\n"
  STDERR << o
  exit(1)
end
if (ARGV.size < 1)
  STDERR << o
  exit(1)
end

ARGV.each {|tpz|
  name = File.basename(tpz, ".tpz")
  STDERR.printf("Processing %s...\n", name)
  dir = name + ".dir"
  system("cmbtc_dump_nonK4PC.py -d -o #{dir} -p EXWTSBC* #{tpz}")
  system("gensvg.py #{dir}")
  system("genhtml.py #{dir}")
  system("mv #{dir}/book.html #{dir}/#{name}.html")
  system("cd #{dir};zip -r ../#{name}.zip #{name}.html img")
  system("rm -r #{dir}")
}
