#!/usr/bin/env ruby

require 'rubygems'
require 'ZFile'
require 'bio'
require 'trollop'

ARGV.push("--help") if ARGV.empty?
opts = Trollop::options do
  banner File.basename($0)
  opt :cds, "Input cds file", :required=>true, :type=>:string
  opt :input, "Input fasta file(s)", :required=>true, :type=>:strings
  opt :gencode, "Genetic code to use", :default=>11, :type=>:integer
  opt :transcript, "Output transcripts, not peptides"
end

starts = Hash.new
stops = Hash.new

opts.input.each do |fasta|
  Bio::FlatFile.new(Bio::FastaFormat, ZFile.new(fasta)).each do |seq|
    File.new(opts.cds).each do |line|
      name, start, stop, comment = line.chomp.split(" ")
      next if name != seq.entry_id
      start = start.to_i
      stop = stop.to_i
      if (start < stop)
        subseq = seq.naseq.subseq(start, stop)
      else
        subseq = seq.naseq.subseq(stop, start).complement
      end
      if (comment)
        header = comment
      else
        header = seq.entry_id + "_" + start.to_s + "_" + stop.to_s
      end
      if (opts.transcript)
        outseq = subseq.upcase
      else
        outseq = subseq.translate(opts.gencode)
      end
      print outseq.to_fasta(header, 60)
    end
  end
end