#!/usr/bin/env ruby

require 'optparse'
require 'ostruct'
require 'rubygems'
require 'ZFile'
require 'bio'

opt = OpenStruct.new
o = OptionParser.new
o.banner << " cds.txt fasta [...fasta...]"
begin
  o.parse!
rescue
  STDERR << $!.message << "\n"
  STDERR << o
  exit(1)
end
if (ARGV.size < 2)
  STDERR << o
  exit(1)
end


starts = Hash.new
stops = Hash.new

cds = ARGV.shift

ARGV.each do |fasta|
  Bio::FlatFile.new(Bio::FastaFormat, ZFile.new(fasta)).each do |seq|
    File.new(cds).each do |line|
      name, start, stop, comment = line.chomp.split(" ")
      next if name != seq.entry_id
      start = start.to_i
      stop = stop.to_i
      if (start < stop)
        subseq = seq.naseq.subseq(start, stop)
      else
        subseq = seq.naseq.subseq(stop, start).complement
      end
      print subseq.translate(1).to_fasta(seq.entry_id + " " + comment.to_s, 60)
    end
  end
end
