#!/usr/bin/env ruby

require 'rubygems'
require 'bio'
require 'optimist'

ARGV.push("--help") if ARGV.empty?
opts = Optimist::options do
  banner File.basename($0)
  opt :code, "NCBI genetic code", :default=>11, :type=>:integer
  opt :glimmer, "glimmer position output", :type=>:string, :required=>true
  opt :input, "fasta file to translate", :type=>:string, :required=>true
end

contig = nil
cds = Hash.new
File.new(opts.glimmer).each do |line|
  if line =~/^>/
    contig = line.chomp.gsub(">","").split(" ").first
    cds[contig] = []
  else
    id, start, stop = line.split(" ")
    coords = [id, start.to_i, stop.to_i]
    cds[contig].push(coords)
  end
end

Bio::FlatFile.new(Bio::FastaFormat, File.new(opts.input)).each do |seq|
  next if cds[seq.entry_id].nil?
  cds[seq.entry_id].each do |orf|
    id, start, stop = orf
    if (start < stop)
      subseq = seq.naseq.subseq(start, stop)
    else
      subseq = seq.naseq.subseq(stop, start).complement
    end
    header =  seq.entry_id + " " + start.to_s + " " + stop.to_s
    print subseq.translate(1, opts.code).to_fasta(header, 60)
  end
end
