#!/usr/bin/env ruby

require 'rubygems'
require 'bio'
require 'apis_lib'
require 'trollop'


ARGV.push("--help") if ARGV.empty?
opts = Trollop::options do
	banner File.basename($0)
  	opt :input, "Input fasta file", :required=>true, :type=>:string
  	opt :fraction, "fraction gaps allowed", :default=>0.1, :type=>:float
  	opt :exclude, "exclude-regexp", :type=>:string
end

trimAlignment(File.basename(opts.input, ".afa") + "_trim.afa", opts.input, opts.fraction, opts.exclude)
