#!/usr/bin/env ruby

require 'rubygems'
require 'Phylogeny'

if (ARGV.size != 2 && ARGV.size != 3)
  STDERR.printf("Usage: %s alignfile fraction-gaps-allowed [exclude-regexp]\n", File.basename($0))
  exit(1)
end

alignment, fraction, exclude = ARGV

trimAlignment(File.basename(alignment, ".afa") + "_trim.afa", alignment, fraction.to_f, exclude)
