#!/usr/bin/env ruby

require 'optimist'
require 'bio'
require 'ZFile'

ARGV.push("--help") if ARGV.empty?
opts = Optimist::options do
  banner File.basename($0)
  opt :input, "input file", :required=>true, :type=>:string
  opt :start, "start position",:required=>true, :type=>:integer
  opt :stop, "stop position",:required=>true, :type=>:integer
end

Bio::FlatFile.new(Bio::FastaFormat, ZFile.new(opts.input)).each do |seq|
  print Bio::Sequence.new(seq.seq[opts.start+1...opts.stop+1]).to_fasta(seq.definition, 60)
end
