#!/usr/bin/env ruby

install = false
if (ARGV.index("-install"))
  ARGV.delete("-install")
  install = true
end

cover = nil
if (ARGV.index("-cover"))
  num = ARGV.index("-cover")
  ARGV.delete("-cover")
  cover = ARGV[num]
  ARGV.delete(cover)
end


if (ARGV.size < 2)
  STDERR.printf("usage: %s [-cover img.jpg] [-install] name file [file..]\n", $0)
  exit(1)
end

name = ARGV.shift
File.symlink(cover, "Cover.jpg") if (cover)

ARGV.each {|file|
  fname = File.basename(file)
  File.symlink(file, fname)
  system("zip -u '#{name}' '#{fname}'")
  File.unlink(fname)
}

if (cover)
  system("zip -u '#{name}' Cover.jpg")
  File.unlink("Cover.jpg")
end

system("cp '#{name}.zip' '/Volumes/Pocket_PC/SDMMC Disk/My Documents/Bookshelf'") if (install)
