#!/usr/bin/env ruby

rev = false
if (ARGV.first == "-r")
  ARGV.shift
  rev = true
end

if (ARGV.size != 2)
  STDERR.printf("usage: %s [-r] in-file alias-file\n", $0)
  exit(1)
end

inF, aliasF = ARGV

realNames = Hash.new

File.new(aliasF).each {|line|
  line.chomp!
  ali, real = line.split("\t")
  if (!rev)
    realNames[ali] = real
  else
    realNames[real] = ali
  end
}

File.new(inF).each {|line|
  realNames.keys.sort {|x, y| y.length <=> x.length}.each {|aliasName|
    line.gsub!(aliasName, realNames[aliasName])
  }
  print line
}

