#!/usr/bin/env ruby

require 'bio'
require 'optimist'
require 'csv'

ARGV.push("--help") if ARGV.empty?
opts = Optimist::options do
  banner File.basename($0)
  opt :input, "name of fasta file(s)", :required=>true, :type=>:strings
  opt :dups, "don't print seqs, print dup.csv"
  opt :keep, "keep headers"
end


names = Hash.new
headers = Hash.new

opts.input.each do |file|
  Bio::FlatFile.new(Bio::FastaFormat, File.new(file)).each do |seq|
    names[seq.seq] = [] if names[seq.seq].nil?
    names[seq.seq].push(seq.entry_id)
    if opts.keep
      headers[seq.seq] = [] if headers[seq.seq].nil?
      headers[seq.seq].push(seq.definition)
    end
  end
end

tot = 0

print ["Gene_Names", "Count", "Seq"].to_csv if opts.dups
names.keys.each do |seq|
  names[seq].sort! {|x, y| x.length <=> y.length}
  name = names[seq].last + "_[#{names[seq].size}]"
  tot += names[seq].size
  if opts.dups
    if names[seq].size > 1
      print [names[seq].join(" "), names[seq].size, seq].to_csv
    end
    print names[seq].join("\t") + "\n" if names[seq].size > 1
  elsif opts.keep
    print seq.to_fasta(headers[seq].first, 60)
  else
    print seq.to_fasta(name, 60)
  end
end

STDERR.printf("%d seqs in %d groups\n", tot, names.keys.size)
