#!/usr/bin/env ruby

require 'ostruct'
require 'optparse'
require 'rubygems'
require 'apis'
require 'csv'
opt = OpenStruct.new

opt.database = "combodb"
opt.host = "mysql-lan-pro.jcvi.org"

ARGV.options {|opts|
  opts.banner << " supergroup.csv"
  opts.on("-d ", "--database ", String, 
         "query database (default #{opt.database})") {|t| opt.database = t}
  opts.on("-h ", "--host ", String, "database host (default #{opt.host})")
  begin
    opts.parse!
  rescue
    STDERR.puts $!.message
    STDERR.puts opts
    exit(1)
  end
  if (ARGV.size != 1)
    STDERR.puts opts
    exit(1)
  end
}

db = MySQL.new(opt.host, opt.database, "jbadger", "plankton")

csv = ARGV.first
CSV.foreach(csv) {|row|
  sp = row[0]
  next if sp == "Species"
  group = row[1]
  STDERR.printf("Setting %s to %s\n", sp, group)
  if (db.count("contigs where species = '#{sp}'") == 0)
    STDERR.printf("sp not found!\n")
  else
    db.query("UPDATE contigs SET supergroup = '#{group}' WHERE species = '#{sp}'")
  end
}
