#!/usr/bin/env ruby

require 'MySQL'
require 'rubygems'
require 'httpclient'


def getTax(species)
  link = "http://www.ncbi.nlm.nih.gov"
  link += "/sites/entrez?db=Taxonomy&cmd=search&term="
  clnt = HTTPClient.new
  species = species.gsub(" ","%20")
  num = 0
  clnt.get(link + species).body.content.split("\n").each {|line|
    if (line =~/wwwtax.cgi\?id=([0-9]+)/)
      num = $1
    end
  }
  sleep 0.2
  return num.to_i
end


db = MySQL.new
Contig.find(:all, :conditions => "taxon_id = 0").each {|contig|
  num = getTax(contig.species)
  if (num > 0)
    contig.taxon_id = num
    contig.save
    printf("Updating %s with taxonid %d\n", contig.species, num)
  end
}
