#!/usr/bin/env ruby

require 'ostruct'
require 'optparse'
opt = OpenStruct.new

ARGV.options {|opts|
  opts.banner << " database coords-file"
  #opts.on(nil, "--report", "run apisReport when done") {|t| opt.report = t}    
  begin
    opts.parse!
  rescue
    STDERR.puts $!.message
    STDERR.puts opts
    exit(1)
  end
  if (ARGV.size != 2)
    STDERR.puts opts
    exit(1)
  end
}

db, coords = ARGV

sql = File.new(db+".sql", "w")
File.new(coords).each {|line|
  name, contig, end5, end3 = line.split("\t")
  contig = contig.split("_").last
  sql.printf("UPDATE asm_feature SET end5  = #{end5} WHERE feat_name='#{name}' AND asmbl_id=#{contig};\n")
  sql.printf("UPDATE asm_feature SET end3 = #{end3} WHERE feat_name='#{name}' AND asmbl_id=#{contig};\n")
}
sql.close
system("sqsh -D #{db} -i #{db}.sql")
