#!/usr/bin/env ruby

require 'trollop'
require 'csv'

ARGV.push("--help") if ARGV.empty?
opts = Trollop::options do
  banner File.basename($0)
  opt :input, "Input csv file", :required=>true, :type=>:string
  opt :lists, "output lists of shared genes", :default=>false
  opt :subset, "fields to include in venn", :type=>:integers
end

name = []
list = []
map = []
orths = Hash.new

CSV.foreach(opts.input) do |fields|
  rep = fields.shift
  if opts.subset
    subset = []
    opts.subset.each do |num|
      subset.push(fields[num - 1])
    end
    fields = subset
  end
  if name.empty?
    fields.size.times do |i|
      map.push(i)
      name.push(fields[i])
      list.push([])
    end
  else
    good = false
    subfields = []
    map.each do |m|
      subfields.push(fields[m])
      good = true if (!fields[m].nil?)
    end
    if good
      orths[rep] = subfields.dup
      subfields.size.times do |i|
        list[i].push(rep) if !subfields[i].nil?
      end
    end
  end
end

only = []
core = []
twoway = []
threeway = []
fourway = []

name.size.times do |i|
  core[i] = list[i].dup
  only[i] = list[i].dup
end

name.size.times do |i|
  name.size.times do |j|
    if i != j
      only[i] -= list[j]
      core[i] = core[i] & list[j]
    end
  end
end

if name.size > 4
  name.size.times do |i|
    fourway[i] = []
    name.size.times do |j|
      if i != j
        fourway[i][j] = []
        name.size.times do |k|
          if k != i && k != j
            fourway[i][j][k] = []
            name.size.times do |l|
              if l != i && l != j && l != k
                fourway[i][j][k][l] = (list[i] & list[j] & list[k] & list[l]) -
                  core[i]
              end
            end
          end
        end
      end
    end
  end
end

if name.size > 3
  name.size.times do |i|
    threeway[i] = []
    name.size.times do |j|
      if i != j
        threeway[i][j] = []
        name.size.times do |k|
          if k != i && k != j
            threeway[i][j][k] = (list[i] & list[j] & list[k])
            threeway[i][j][k] -= core[i]
            name.size.times do |l|
              if l != i && l != j && l != k && name.size > 4
                threeway[i][j][k] -= fourway[i][j][k][l]
              end
            end
          end
        end
      end
    end
  end
end

name.size.times do |i|
  twoway[i] = []
  name.size.times do |j|
    if i != j
      twoway[i][j] = (list[i] & list[j]) - core[i]
      name.size.times do |k|
        if k != i && k != j && name.size > 3
          twoway[i][j] -= threeway[i][j][k]
          name.size.times do |l|
            if l != i && l != j && l != k && name.size > 4
              twoway[i][j] -= fourway[i][j][k][l]
            end
          end
        end
      end
    end
  end
end


def printArray(list, i, orths, file)
  fp = File.new(file, "w")
  list.each do |entry|
    fp.printf("%s\n", orths[entry][i])
  end
  fp.close
end


if opts.lists
  name.size.times do |i|
    printArray(core[i], i, orths, name[i] + "_core.txt")
    printArray(only[i], i, orths, name[i] + "_only.txt")
    name.size.times do |j|
      if i != j
        printArray(twoway[i][j], i, orths, name[i] + "+" + name[j] + ".txt")
        (j + 1).upto(name.size - 1) do |k|
          if k != i && name.size > 3
            printArray(threeway[i][j][k], i, orths, name[i] + "+" + name[j] + "+" + name[k] + ".txt")
            (k + 1).upto(name.size - 1) do |l|
              if l != i && l != j && name.size > 4
                printArray(fourway[i][j][k][l], i, orths, name[i] + "+" + 
                           name[j] + "+" + name[k] + "+" + name[l] + ".txt")
              end
            end
          end
        end
      end
    end
  end
end

if name.size == 3
  venn = eval(DATA.read)["venn3"]
elsif name.size == 4
  venn = eval(DATA.read)["venn4"]
elsif name.size == 5
  venn = eval(DATA.read)["venn5"]
end


key = ["A","B","C","D","E"]

name.size.times do |i|
  venn.gsub!(key[i]+"namestring", name[i])
  venn.gsub!(key[i]+"only", only[i].size.to_s)
  venn.gsub!(key[i]+"total", list[i].size.to_s)
  name.size.times do |j|
    if i != j
      venn.gsub!(">" + key[i]+key[j]+"<", 
                 ">" + twoway[i][j].size.to_s + "<")
      name.size.times do |k|
        if k != i && k != j && name.size > 3
          venn.gsub!(">" + key[i]+key[j]+key[k] + "<", 
                     ">" + threeway[i][j][k].size.to_s + "<")
          name.size.times do |l|
            if l != i && l != j && l != k && name.size > 4
              venn.gsub!(">" + key[i]+key[j]+key[k]+key[l]+ "<", 
                         ">" + fourway[i][j][k][l].size.to_s + "<")
            end
          end
        end
      end
    end
  end
end

if name.size == 3
  venn.gsub!("ABC", core[0].size.to_s)
elsif name.size == 4
  venn.gsub!("ABCD", core[0].size.to_s)
elsif name.size == 5
  venn.gsub!("ABCDE", core[0].size.to_s)
end

print venn

__END__
venn  = {"venn3" => '<?xml version="1.0"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
         "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink">
  <circle cx="310" cy="210" r="100"
	  fill="red" stroke="black" stroke-width="1" fill-opacity="0.5" />
  <circle cx="210" cy="210" r="100"
	  fill="blue" stroke="black" stroke-width="1" fill-opacity="0.5" />
  <circle cx="260" cy="310" r="100"
	  fill="green" stroke="black" stroke-width="1" fill-opacity="0.5" />

  <text x="160" y="75" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >Atotal</text>  
  <text x="160" y="90" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >Anamestring</text>
  <text x="350" y="75" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >Btotal</text>
  <text x="350" y="90" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >Bnamestring</text>
  <text x="260" y="440" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >Cnamestring</text>
  <text x="260" y="455" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >Ctotal</text>

  <text x="160" y="200" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >Aonly</text>
  <text x="360" y="200" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >Bonly</text>
  <text x="260" y="350" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >Conly</text>
  
  <text x="260" y="175" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >AB</text>
  <text x="200" y="275" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >AC</text>
  <text x="320" y="275" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >BC</text>
  
  <text x="260" y="250" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >ABC</text>
</svg>',

"venn4"=>'<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
         "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink">
  <g transform="translate(150,250)">
  <g transform="rotate(30)">
  <ellipse cx="0" cy="0" rx="150" ry="75" 
	  fill="red" stroke="black" stroke-width="1" fill-opacity="0.5" />
  </g>
  </g>
  <g transform="translate(300,250)">
  <g transform="rotate(-30)">
  <ellipse cx="0" cy="0" rx="150" ry="75" 
	  fill="blue" stroke="black" stroke-width="1" fill-opacity="0.5" />
  </g>
  </g>
  <g transform="translate(210,210)">
  <g transform="rotate(60)">
  <ellipse cx="0" cy="0" rx="150" ry="75" 
	  fill="green" stroke="black" stroke-width="1" fill-opacity="0.5" />
  </g>
  </g>
  <g transform="translate(240,210)">
  <g transform="rotate(-60)">
  <ellipse cx="0" cy="0" rx="150" ry="75" 
	  fill="yellow" stroke="black" stroke-width="1" fill-opacity="0.5" />
  </g>
  </g>
  <text x="50" y="120" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >Atotal</text>  
  <text x="50" y="135" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >Anamestring</text>
  <text x="150" y="50" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >Btotal</text>
  <text x="150" y="65" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >Bnamestring</text>
<text x="290" y="50" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >Ctotal</text>
  <text x="290" y="65" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >Cnamestring</text>
  <text x="400" y="120" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >Dtotal</text>  
  <text x="400" y="135" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >Dnamestring</text>

  <text x="80" y="200" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >Aonly</text>
  <text x="150" y="120" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >Bonly</text>
  <text x="290" y="120" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >Conly</text>
  <text x="380" y="200" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >Donly</text>
  <text x="140" y="200" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >AB</text>
  <text x="155" y="300" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >AC</text>
  <text x="230" y="160" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >BC</text>
  <text x="295" y="300" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >BD</text>
  <text x="230" y="280" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >ABCD</text>
  <text x="225" y="345" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >AD</text>
  <text x="310" y="200" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >CD</text>
  <text x="180" y="220" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >ABC</text>
  <text x="270" y="220" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >BCD</text>
  <text x="180" y="320" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >ACD</text>
  <text x="265" y="320" text-anchor="middle" font-family="Verdana" font-size="10" fill="black" >ABD</text>
  </svg>',
'venn5' =>'<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="746" height="742" viewBox="-362 -388 776 742">
 <desc>5-way Venn Devised by Branko Gruenbaum and rendered by CMG Lee.</desc>
 <defs>
  <ellipse id="ellipse" cx="36" cy="-56" rx="160" ry="320" />
  <g id="ellipses">
   <use xlink:href="#ellipse" fill="#0000ff" />
   <use xlink:href="#ellipse" fill="#0099ff" transform="rotate(72)" />
   <use xlink:href="#ellipse" fill="#00cc00" transform="rotate(144)" />
   <use xlink:href="#ellipse" fill="#cc9900" transform="rotate(216)" />
   <use xlink:href="#ellipse" fill="#ff0000" transform="rotate(288)" />
  </g>
 </defs>
 <use xlink:href="#ellipses" fill-opacity="0.3" />
 <use xlink:href="#ellipses" fill-opacity="0" stroke="#000" stroke-width="2" />
 <g text-anchor="middle" font-family="sans-serif" font-size="16">
  <text x="30"   y="-300" dy="0.7ex">Aonly</text>
  <text x="200"  y="-330" dy="0.7ex">Anamestring</text>
  <text x="200"  y="-350" dy="0.7ex">Atotal</text>
  <text x="300"  y="-60"  dy="0.7ex">Bonly</text>
  <text x="290"  y="-180"  dy="0.7ex">Bnamestring</text>
  <text x="290"  y="-200"  dy="0.7ex">Btotal</text>
  <text x="320"  y="160"  dy="0.7ex">Ctotal</text>
  <text x="320"  y="180"  dy="0.7ex">Cnamestring</text>
  <text x="160"  y="280"  dy="0.7ex">Conly</text>
  <text x="-220" y="220"  dy="0.7ex">Donly</text>
  <text x="-220" y="340"  dy="0.7ex">Dnamestring</text>
  <text x="-220" y="320"  dy="0.7ex">Dtotal</text>
  <text x="-280" y="-130" dy="0.7ex">Eonly</text>
  <text x="-240" y="-250" dy="0.7ex">Enamestring</text>
  <text x="-240" y="-270" dy="0.7ex">Etotal</text>
  <text x="180"  y="-130" dy="0.7ex">AB</text>
  <text x="40"   y="230"  dy="0.7ex">AC</text>
  <text x="100"  y="-200" dy="0.7ex">AD</text>
  <text x="-80"  y="-215" dy="0.7ex">AE</text>
  <text x="190"  y="125"  dy="0.7ex">BC</text>
  <text x="-190" y="120"  dy="0.7ex">BD</text>
  <text x="230"  y="40"   dy="0.7ex">BE</text>
  <text x="-60"  y="220"  dy="0.7ex">CD</text>
  <text x="-170" y="-150" dy="0.7ex">CE</text>
  <text x="-222" y="0"    dy="0.7ex">DE</text>
  <text x="90"   y="150"  dy="0.7ex">ABC</text>
  <text x="148"  y="-153" dy="0.7ex">ABD</text>
  <text x="170"  y="-20"  dy="0.7ex">ABE</text>
  <text x="-33"  y="208"  dy="0.7ex">ACD</text>
  <text x="-93"  y="-193" dy="0.7ex">ACE</text>
  <text x="20"   y="-180" dy="0.7ex">ADE</text>
  <text x="-120" y="120"  dy="0.7ex">BCD</text>
  <text x="190"  y="100"  dy="0.7ex">BCE</text>
  <text x="-211" y="32"   dy="0.7ex">BDE</text>
  <text x="-150" y="-80"  dy="0.7ex">CDE</text>
  <text x="-30"  y="160"  dy="0.7ex">ABCD</text>
  <text x="140"  y="80"   dy="0.7ex">ABCE</text>
  <text x="120"  y="-100" dy="0.7ex">ABDE</text>
  <text x="-60"  y="-140" dy="0.7ex">ACDE</text>
  <text x="-160" y="20"   dy="0.7ex">BCDE</text>
  <text x="0"    y="0"    dy="0.7ex">ABCDE</text>
 </g>
</svg>'}


