#!/usr/bin/env ruby

require 'optimist'

ARGV.push("--help") if ARGV.empty?
opts = Optimist::options do
  banner File.basename($0)
  opt :input, "input file", :required=>true, :type=>:string
  opt :debug, "debugging mode", :default => false
end

registers = [0, 0, 0, 0, 0, 0, 0, 0]
ops = ["inc", "dec", "jmp", "isz", "stp", "prt", "inp"]

lines = File.read(opts.input).split("\n")
pc = 0
while pc < lines.length
  lines[pc] = lines[pc].to_s.split(";").first # comments after ;
  if lines[pc]  == "" || lines[pc] =~/^:/
	pc = pc + 1
	next
  end
  op, val = lines[pc].chomp.split(" ")
  if !ops.include? op
    STDERR << op << " is not a valid wdr op code\n"
    exit(1)
  end
  if val =~/^:/ # label
    val = lines.index(val) + 1
  end
  val = val.to_i
  if val < 0 || val > 7
    STDERR << val << " is an illegal register\n"
    exit(1)
  end
  print lines[pc] + "\t" + registers.to_s + "\n" if opts.debug
  if op == "inc"
    registers[val] += 1
  elsif op == "dec"
    registers[val] -= 1
  elsif op == "jmp"
    pc = val
    next
  elsif op == "isz"
    if (registers[val] == 0)
      pc += 1
    end
  elsif op == "stp"
    break
  elsif op == "prt"
    print registers[val]
    print "\n"
  elsif op == "inp"
	registers[val] = STDIN.read.to_i
  end
  pc += 1
end
