#!/usr/bin/env ruby

require 'optimist'

ARGV.push("--help") if ARGV.empty?
opts = Optimist::options do
  banner File.basename($0)
  opt :input, "input file", :required=>true, :type=>:string
  opt :debug, "debugging mode", :default => false
end

# Initialize registers to 0
registers = [0] * 8

# Define operation codes as lambdas.  Each lambda takes register value as input.
ops = {
  inc: -> (r) { r += 1 },
  dec: -> (r) { r -= 1 },
  clr: -> (r) { 0 },
  jmp: -> (r) { r },  # handle this in loop below
  isz: -> (r) { r }, # handle this in loop below
  rts: -> (r) { r }, # handle this in loop below
  stp: -> (r) { exit }, # Properly end program
  prt: -> (r) { print r,"\n"; r},
  inp: -> (r) { r = STDIN.read.to_i; r }
}

lines = File.read(opts.input).split("\n").
          collect{|l| l.split(";").first} # get lines, remove comments

lines = lines.select{|l| !l.nil? && l!=""} # remove empty lines

# Label Definition Phase
labels = {}
0.upto(lines.length - 1) do |i|
  line = lines[i]
  if line.start_with?(":")
    label_name = line[1..-1].strip
    labels[label_name] = i
    lines[i] = "" # get rid of label line
  end
end

lines = lines.select{|l| !l.nil? && l!=""} # remove empty lines

# replace labels with line numbers
lines = lines.collect{|l| 
  labels.keys.each do |lbl|
    l = l.sub(lbl, labels[lbl].to_s)
  end
  l
}

debug_str = ""
pc = 0
opc = 0
while pc < lines.length
  line = lines[pc] # Get the full line for error reporting
  op, val_str = line.split(" ")  # Split the line
  val = val_str.to_i
  debug_str = registers.to_s + "\t" + line + "\t" if opts.debug

  if val < 0 || val > registers.length - 1
    STDERR << "Illegal register number " << val.to_s <<
      " at line " << pc << ": " << line << "\n"
    exit(1)
  end

  if ops.key?(op.to_sym)
    if op == "jmp"
	  opc = pc
      pc = val
      next
    elsif op == "rts"
	  pc = opc + 1
      next
    elsif op == "isz"
      pc += 1 if registers[val] == 0
    else
      registers[val] = ops[op.to_sym].call(registers[val])
    end
  else
    STDERR << "Illegal op code " << op << " at line " <<
      pc << ": " << line << "\n"
    exit(1)
  end
  print debug_str + registers.to_s + "\n" if opts.debug
  pc += 1
end
