#!/usr/bin/env ruby 

require 'rubygems'
require 'bio'    
require 'optparse'
require 'ostruct'

opt = OpenStruct.new
opt.remove = false
opt.header = false

o = OptionParser.new
o.banner << " pep att"
begin
  o.parse!
rescue
  STDERR << $!.message << "\n"
  STDERR << o
  exit(1)
end
if (ARGV.size != 2)
  STDERR << o
  exit(1)
end

pep, att = ARGV


species = Hash.new
taxonomy = Hash.new
taxid = Hash.new

File.new(att).each {|line|
  acc, len, org, strain, id, tax, form, proteins, rrnas, gc = line.chomp.tr("'","").split("\t")
  species[acc] = org
  
  if (tax !~/strain/)
    t = tax.split(";")
    t.pop
    tax = ""
    t.each {|l|
      tax += l + "; "
    }
    tax += org
  end
  taxonomy[acc] = tax  
  taxid[acc] = id
}

Bio::FlatFile.new(Bio::FastaFormat, File.new(pep)).each {|seq|
  name = seq.entry_id
  contig = name.split("-").last
  prot = seq.seq
  ann = seq.definition.tr("'\"\\","").split(" ", 2).last.split(" {").first
  printf("%s\t%s\t%d\t%s\t%s\t%s\n", seq.entry_id, contig, taxid[contig], taxonomy[contig], ann, prot)
}
